#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AfterImageMesh

#include "Basic.hpp"

#include "AfterImageMesh_classes.hpp"
#include "AfterImageMesh_parameters.hpp"


namespace SDK
{

// Function AfterImageMesh.AfterImageMesh_C.Initialize
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          bpp__OwnerObject__pf                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__return__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AAfterImageMesh_C::Initialize(class UObject* bpp__OwnerObject__pf, bool* bpp__return__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AfterImageMesh_C", "Initialize");

	Params::AfterImageMesh_C_Initialize Parms{};

	Parms.bpp__OwnerObject__pf = bpp__OwnerObject__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__return__pf != nullptr)
		*bpp__return__pf = Parms.bpp__return__pf;
}


// Function AfterImageMesh.AfterImageMesh_C.ReceiveTick
// (Native, Event, Public)
// Parameters:
// float                                   bpp__DeltaSeconds__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AAfterImageMesh_C::ReceiveTick(float bpp__DeltaSeconds__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AfterImageMesh_C", "ReceiveTick");

	Params::AfterImageMesh_C_ReceiveTick Parms{};

	Parms.bpp__DeltaSeconds__pf = bpp__DeltaSeconds__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function AfterImageMesh.AfterImageMesh_C.SetSkeletalMeshinfo
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class USkeletalMesh*                    bpp__SkeletalMesh__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UClass*                           bpp__AnimInstanceClass__pf                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UMaterialInterface*               bpp__OptionalReplacementMaterial__pf                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__return__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AAfterImageMesh_C::SetSkeletalMeshinfo(class USkeletalMesh* bpp__SkeletalMesh__pf, class UClass* bpp__AnimInstanceClass__pf, class UMaterialInterface* bpp__OptionalReplacementMaterial__pf, bool* bpp__return__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AfterImageMesh_C", "SetSkeletalMeshinfo");

	Params::AfterImageMesh_C_SetSkeletalMeshinfo Parms{};

	Parms.bpp__SkeletalMesh__pf = bpp__SkeletalMesh__pf;
	Parms.bpp__AnimInstanceClass__pf = bpp__AnimInstanceClass__pf;
	Parms.bpp__OptionalReplacementMaterial__pf = bpp__OptionalReplacementMaterial__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__return__pf != nullptr)
		*bpp__return__pf = Parms.bpp__return__pf;
}


// Function AfterImageMesh.AfterImageMesh_C.StartAfterImage
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// float                                   bpp__Time__pf                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__return__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AAfterImageMesh_C::StartAfterImage(float bpp__Time__pf, bool* bpp__return__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AfterImageMesh_C", "StartAfterImage");

	Params::AfterImageMesh_C_StartAfterImage Parms{};

	Parms.bpp__Time__pf = bpp__Time__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__return__pf != nullptr)
		*bpp__return__pf = Parms.bpp__return__pf;
}

}

