#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArchiveDiaryListItem

#include "Basic.hpp"

#include "ArchiveDiaryListItem_classes.hpp"
#include "ArchiveDiaryListItem_parameters.hpp"


namespace SDK
{

// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.ExecuteUbergraph_ArchiveDiaryListItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UArchiveDiaryListItem_C::ExecuteUbergraph_ArchiveDiaryListItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "ExecuteUbergraph_ArchiveDiaryListItem");

	Params::ArchiveDiaryListItem_C_ExecuteUbergraph_ArchiveDiaryListItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UArchiveDiaryListItem_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UArchiveDiaryListItem_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UArchiveDiaryListItem_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.SetDiaryData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPBArchiveDiaryCatalogData&input_data                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UArchiveDiaryListItem_C::SetDiaryData(const struct FPBArchiveDiaryCatalogData& input_data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "SetDiaryData");

	Params::ArchiveDiaryListItem_C_SetDiaryData Parms{};

	Parms.input_data = std::move(input_data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.SetNameText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      input_text                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UArchiveDiaryListItem_C::SetNameText(const class FText& input_text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "SetNameText");

	Params::ArchiveDiaryListItem_C_SetNameText Parms{};

	Parms.input_text = std::move(input_text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ArchiveDiaryListItem.ArchiveDiaryListItem_C.SetDispCursor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsOn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UArchiveDiaryListItem_C::SetDispCursor(bool IsOn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveDiaryListItem_C", "SetDispCursor");

	Params::ArchiveDiaryListItem_C_SetDispCursor Parms{};

	Parms.IsOn = IsOn;

	UObject::ProcessEvent(Func, &Parms);
}

}

