#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GhostTrailManager

#include "Basic.hpp"

#include "BP_GhostTrailManager_classes.hpp"
#include "BP_GhostTrailManager_parameters.hpp"


namespace SDK
{

// Function BP_GhostTrailManager.BP_GhostTrailManager_C.AddMeshToTrail
// (Native, Public, BlueprintCallable)
// Parameters:
// class UMeshComponent*                   bpp__Mesh__pf                                          (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_GhostTrailManager_C::AddMeshToTrail(class UMeshComponent* bpp__Mesh__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "AddMeshToTrail");

	Params::BP_GhostTrailManager_C_AddMeshToTrail Parms{};

	Parms.bpp__Mesh__pf = bpp__Mesh__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.CalcVelocities
// (Native, Public, BlueprintCallable)

void ABP_GhostTrailManager_C::CalcVelocities()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "CalcVelocities");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.ReceiveTick
// (Native, Event, Public)
// Parameters:
// float                                   bpp__DeltaSeconds__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_GhostTrailManager_C::ReceiveTick(float bpp__DeltaSeconds__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "ReceiveTick");

	Params::BP_GhostTrailManager_C_ReceiveTick Parms{};

	Parms.bpp__DeltaSeconds__pf = bpp__DeltaSeconds__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.RevealLastGhosts
// (Native, Public, BlueprintCallable)

void ABP_GhostTrailManager_C::RevealLastGhosts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "RevealLastGhosts");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.SetGhostMaterialParams
// (Native, Public, BlueprintCallable)
// Parameters:
// const struct FE_GhostInfo&              bpp__Ghost__pf                                         (Parm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_GhostTrailManager_C::SetGhostMaterialParams(const struct FE_GhostInfo& bpp__Ghost__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "SetGhostMaterialParams");

	Params::BP_GhostTrailManager_C_SetGhostMaterialParams Parms{};

	Parms.bpp__Ghost__pf = std::move(bpp__Ghost__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.SpawnGhosts
// (Native, Public, BlueprintCallable)

void ABP_GhostTrailManager_C::SpawnGhosts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "SpawnGhosts");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.SpawnSkeletalGhost
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class USkeletalMeshComponent*           bpp__MasterStaticMeshComponent__pf                     (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FE_GhostInfo*                    bpp__GhostInfo__pf                                     (Parm, OutParm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_GhostTrailManager_C::SpawnSkeletalGhost(class USkeletalMeshComponent* bpp__MasterStaticMeshComponent__pf, struct FE_GhostInfo* bpp__GhostInfo__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "SpawnSkeletalGhost");

	Params::BP_GhostTrailManager_C_SpawnSkeletalGhost Parms{};

	Parms.bpp__MasterStaticMeshComponent__pf = bpp__MasterStaticMeshComponent__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__GhostInfo__pf != nullptr)
		*bpp__GhostInfo__pf = std::move(Parms.bpp__GhostInfo__pf);
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.SpawnStaticGhost
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UStaticMeshComponent*             bpp__MasterStaticMeshComponent__pf                     (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FE_GhostInfo*                    bpp__GhostInfo__pf                                     (Parm, OutParm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_GhostTrailManager_C::SpawnStaticGhost(class UStaticMeshComponent* bpp__MasterStaticMeshComponent__pf, struct FE_GhostInfo* bpp__GhostInfo__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "SpawnStaticGhost");

	Params::BP_GhostTrailManager_C_SpawnStaticGhost Parms{};

	Parms.bpp__MasterStaticMeshComponent__pf = bpp__MasterStaticMeshComponent__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__GhostInfo__pf != nullptr)
		*bpp__GhostInfo__pf = std::move(Parms.bpp__GhostInfo__pf);
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.SpawnTimer
// (Native, Public, BlueprintCallable)

void ABP_GhostTrailManager_C::SpawnTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "SpawnTimer");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.UpdateGhostInfos
// (Native, Public, BlueprintCallable)

void ABP_GhostTrailManager_C::UpdateGhostInfos()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "UpdateGhostInfos");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_GhostTrailManager.BP_GhostTrailManager_C.UpdateGhostVisual
// (Native, Public, BlueprintCallable)
// Parameters:
// const struct FE_GhostInfo&              bpp__GhostInfo__pf                                     (Parm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_GhostTrailManager_C::UpdateGhostVisual(const struct FE_GhostInfo& bpp__GhostInfo__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GhostTrailManager_C", "UpdateGhostVisual");

	Params::BP_GhostTrailManager_C_UpdateGhostVisual Parms{};

	Parms.bpp__GhostInfo__pf = std::move(bpp__GhostInfo__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

