#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_DialogueDatatableHost

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// DynamicClass BPI_DialogueDatatableHost.BPI_DialogueDatatableHost_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_DialogueDatatableHost_C final
{
public:
	void GetAsset(class FName bpp__ItemName__pf, struct FNamedAsset* bpp__AssetReference__pf, bool* bpp__Found__pf);
	void GetDialogueItem(class FName bpp__ItemName__pf, struct FDialogue_TableItem* bpp__Item__pf, bool* bpp__Found__pf);
	void GetDialogueRowNames(TArray<class FName>* bpp__Names__pf);
	void GetScriptInterpreter(class ABP_ScriptInterpreter_C** bpp__Interpreter__pf);
	void GetSpeakerAttributes(class FName bpp__SpeakerID__pf, struct FDialogueSpeakerAttribute_TableItem* bpp__Result__pf, bool* bpp__Found__pf);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BPI_DialogueDatatableHost_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_DialogueDatatableHost_C")
	}
	static class IBPI_DialogueDatatableHost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_DialogueDatatableHost_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_DialogueDatatableHost_C;

}

