#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Chaos_Invite_Match

#include "Basic.hpp"

#include "Chaos_Invite_Match_classes.hpp"
#include "Chaos_Invite_Match_parameters.hpp"


namespace SDK
{

// Function Chaos_Invite_Match.Chaos_Invite_Match_C.ExecuteUbergraph_Chaos_Invite_Match
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::ExecuteUbergraph_Chaos_Invite_Match(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "ExecuteUbergraph_Chaos_Invite_Match");

	Params::Chaos_Invite_Match_C_ExecuteUbergraph_Chaos_Invite_Match Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Tick");

	Params::Chaos_Invite_Match_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.ClearJoinSessionComplete
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::ClearJoinSessionComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "ClearJoinSessionComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Auto-MatchmakingComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOCGameSession*                   OCGameSession_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsHost                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::Auto_MatchmakingComplete(class AOCGameSession* OCGameSession_0, bool bWasSuccessful, bool bIsHost)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Auto-MatchmakingComplete");

	Params::Chaos_Invite_Match_C_Auto_MatchmakingComplete Parms{};

	Parms.OCGameSession_0 = OCGameSession_0;
	Parms.bWasSuccessful = bWasSuccessful;
	Parms.bIsHost = bIsHost;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.EnterOnlineRematchState
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::EnterOnlineRematchState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "EnterOnlineRematchState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.JoinFriendSessionComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::JoinFriendSessionComplete(const class FString& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "JoinFriendSessionComplete");

	Params::Chaos_Invite_Match_C_JoinFriendSessionComplete Parms{};

	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.SetupJoinFriendSessionComplete
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::SetupJoinFriendSessionComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "SetupJoinFriendSessionComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.OnNetworkFailure
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ENetworkFailure                         FailureType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsServer                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::OnNetworkFailure(ENetworkFailure FailureType, bool IsServer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "OnNetworkFailure");

	Params::Chaos_Invite_Match_C_OnNetworkFailure Parms{};

	Parms.FailureType = FailureType;
	Parms.IsServer = IsServer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.UnbindNetworkConnectionStatusChange
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::UnbindNetworkConnectionStatusChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "UnbindNetworkConnectionStatusChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.BindNetworkConnectionStatusChange
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::BindNetworkConnectionStatusChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "BindNetworkConnectionStatusChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.OnNetworkConnectionStatusChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EeOnlineServerConnectionStatus          LastConnectionStatus                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EeOnlineServerConnectionStatus          ConnectionStatus                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::OnNetworkConnectionStatusChange(EeOnlineServerConnectionStatus LastConnectionStatus, EeOnlineServerConnectionStatus ConnectionStatus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "OnNetworkConnectionStatusChange");

	Params::Chaos_Invite_Match_C_OnNetworkConnectionStatusChange Parms{};

	Parms.LastConnectionStatus = LastConnectionStatus;
	Parms.ConnectionStatus = ConnectionStatus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.StopUpdateListing
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::StopUpdateListing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "StopUpdateListing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.SetInviteState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EChaosInviteState                       NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::SetInviteState(EChaosInviteState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "SetInviteState");

	Params::Chaos_Invite_Match_C_SetInviteState Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.CompleteFriendsListUpdate_Matchmaking
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOCGameSession*                   OCGameSession_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::CompleteFriendsListUpdate_Matchmaking(class AOCGameSession* OCGameSession_0, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "CompleteFriendsListUpdate_Matchmaking");

	Params::Chaos_Invite_Match_C_CompleteFriendsListUpdate_Matchmaking Parms{};

	Parms.OCGameSession_0 = OCGameSession_0;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.UpdateListing_MatchMaking
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::UpdateListing_MatchMaking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "UpdateListing_MatchMaking");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.JoinSessionComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::JoinSessionComplete(const class FString& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "JoinSessionComplete");

	Params::Chaos_Invite_Match_C_JoinSessionComplete Parms{};

	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.SetupJoinSessionComplete
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::SetupJoinSessionComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "SetupJoinSessionComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.CreateSessionComplete
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOCGameSession*                   OCGameSession_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::CreateSessionComplete(class AOCGameSession* OCGameSession_0, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "CreateSessionComplete");

	Params::Chaos_Invite_Match_C_CreateSessionComplete Parms{};

	Parms.OCGameSession_0 = OCGameSession_0;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.SetupCreateSessionComplete
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::SetupCreateSessionComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "SetupCreateSessionComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Reset
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Create Session Matchmaking
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::Create_Session_Matchmaking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Create Session Matchmaking");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.UpdateVisibility
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::UpdateVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "UpdateVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.BreakSearch
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::BreakSearch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "BreakSearch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.AllowRefresh
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::AllowRefresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "AllowRefresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.FriendSession
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::FriendSession()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "FriendSession");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UChaos_Invite_Match_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.LoadList
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::LoadList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "LoadList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.FriendList
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::FriendList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "FriendList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UChaos_Invite_Match_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.UpdateListing
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::UpdateListing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "UpdateListing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.CompleteFriendsListUpdate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOCGameSession*                   OCGameSession_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::CompleteFriendsListUpdate(class AOCGameSession* OCGameSession_0, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "CompleteFriendsListUpdate");

	Params::Chaos_Invite_Match_C_CompleteFriendsListUpdate Parms{};

	Parms.OCGameSession_0 = OCGameSession_0;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.CullFullGames
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FOnlineServerListing>&All                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UChaos_Invite_Match_C::CullFullGames(const TArray<struct FOnlineServerListing>& All)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "CullFullGames");

	Params::Chaos_Invite_Match_C_CullFullGames Parms{};

	Parms.All = std::move(All);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.PickRandomGameAndJoin
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FOnlineServerListing>&Games                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UChaos_Invite_Match_C::PickRandomGameAndJoin(const TArray<struct FOnlineServerListing>& Games)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "PickRandomGameAndJoin");

	Params::Chaos_Invite_Match_C_PickRandomGameAndJoin Parms{};

	Parms.Games = std::move(Games);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.FindSessionOverTime
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::FindSessionOverTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "FindSessionOverTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.BackEvent
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::BackEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "BackEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.OnClose
// (BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::OnClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "OnClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.OnOpen
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPBGameModeType                         GameMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::OnOpen(EPBGameModeType GameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "OnOpen");

	Params::Chaos_Invite_Match_C_OnOpen Parms{};

	Parms.GameMode = GameMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.OnPressedButton
// (Event, Public, BlueprintEvent)

void UChaos_Invite_Match_C::OnPressedButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "OnPressedButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Start
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>&OnStepChanged                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
// int32                                   ZOrder                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::Start(const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>& OnStepChanged, int32 ZOrder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Start");

	Params::Chaos_Invite_Match_C_Start Parms{};

	Parms.OnStepChanged = OnStepChanged;
	Parms.ZOrder = ZOrder;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPBGameModeType                         GameMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::Initialize(EPBGameModeType GameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Initialize");

	Params::Chaos_Invite_Match_C_Initialize Parms{};

	Parms.GameMode = GameMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.UpdateControlGuide
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsAllowConfirm                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::UpdateControlGuide(bool IsAllowConfirm)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "UpdateControlGuide");

	Params::Chaos_Invite_Match_C_UpdateControlGuide Parms{};

	Parms.IsAllowConfirm = IsAllowConfirm;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.MoveCursor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Move                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::MoveCursor(int32 Move)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "MoveCursor");

	Params::Chaos_Invite_Match_C_MoveCursor Parms{};

	Parms.Move = Move;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.CloseMenu
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ForceHostClose                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::CloseMenu(bool ForceHostClose)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "CloseMenu");

	Params::Chaos_Invite_Match_C_CloseMenu Parms{};

	Parms.ForceHostClose = ForceHostClose;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.GameIsFull
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FOnlineServerListing&      OnlineServerListing                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool*                                   Full                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::GameIsFull(const struct FOnlineServerListing& OnlineServerListing, bool* Full)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "GameIsFull");

	Params::Chaos_Invite_Match_C_GameIsFull Parms{};

	Parms.OnlineServerListing = std::move(OnlineServerListing);

	UObject::ProcessEvent(Func, &Parms);

	if (Full != nullptr)
		*Full = Parms.Full;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.GetSelectFriend
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UOCFriendListUnit_C**             Out                                                    (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UChaos_Invite_Match_C::GetSelectFriend(class UOCFriendListUnit_C** Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "GetSelectFriend");

	Params::Chaos_Invite_Match_C_GetSelectFriend Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.BackToMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::BackToMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "BackToMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.SetFriendsFoundMessage
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    inFriendsFound                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::SetFriendsFoundMessage(bool inFriendsFound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "SetFriendsFoundMessage");

	Params::Chaos_Invite_Match_C_SetFriendsFoundMessage Parms{};

	Parms.inFriendsFound = inFriendsFound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.IsWaitingMatchmaking
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Searching                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::IsWaitingMatchmaking(bool* Searching)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "IsWaitingMatchmaking");

	Params::Chaos_Invite_Match_C_IsWaitingMatchmaking Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Searching != nullptr)
		*Searching = Parms.Searching;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.IsHostRoomBlockedByClient
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    NameOrID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool*                                   HostByBlocked                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::IsHostRoomBlockedByClient(const class FString& NameOrID, bool* HostByBlocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "IsHostRoomBlockedByClient");

	Params::Chaos_Invite_Match_C_IsHostRoomBlockedByClient Parms{};

	Parms.NameOrID = std::move(NameOrID);

	UObject::ProcessEvent(Func, &Parms);

	if (HostByBlocked != nullptr)
		*HostByBlocked = Parms.HostByBlocked;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.IsClientBlockedByHostRoom
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FString>&                  RoomBlockedPlayers                                     (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
// bool*                                   IsClientBlocked                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::IsClientBlockedByHostRoom(TArray<class FString>& RoomBlockedPlayers, bool* IsClientBlocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "IsClientBlockedByHostRoom");

	Params::Chaos_Invite_Match_C_IsClientBlockedByHostRoom Parms{};

	Parms.RoomBlockedPlayers = std::move(RoomBlockedPlayers);

	UObject::ProcessEvent(Func, &Parms);

	RoomBlockedPlayers = std::move(Parms.RoomBlockedPlayers);

	if (IsClientBlocked != nullptr)
		*IsClientBlocked = Parms.IsClientBlocked;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.CanCancelFriendsListStep
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   CanCancel                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::CanCancelFriendsListStep(bool* CanCancel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "CanCancelFriendsListStep");

	Params::Chaos_Invite_Match_C_CanCancelFriendsListStep Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanCancel != nullptr)
		*CanCancel = Parms.CanCancel;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.FindSessionUpdateStatusLoc
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString*                          OutputStatus                                           (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// bool*                                   IsSearching                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::FindSessionUpdateStatusLoc(const class FString& Status, class FString* OutputStatus, bool* IsSearching)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "FindSessionUpdateStatusLoc");

	Params::Chaos_Invite_Match_C_FindSessionUpdateStatusLoc Parms{};

	Parms.Status = std::move(Status);

	UObject::ProcessEvent(Func, &Parms);

	if (OutputStatus != nullptr)
		*OutputStatus = std::move(Parms.OutputStatus);

	if (IsSearching != nullptr)
		*IsSearching = Parms.IsSearching;
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.StartSwitchAutoMatchmaking
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::StartSwitchAutoMatchmaking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "StartSwitchAutoMatchmaking");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.HandleSuccessfulSwitchAutoMatchmaking
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHost                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UChaos_Invite_Match_C::HandleSuccessfulSwitchAutoMatchmaking(bool IsHost)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "HandleSuccessfulSwitchAutoMatchmaking");

	Params::Chaos_Invite_Match_C_HandleSuccessfulSwitchAutoMatchmaking Parms{};

	Parms.IsHost = IsHost;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.HandleFailureSwitchAutoMatchmakingPt1
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::HandleFailureSwitchAutoMatchmakingPt1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "HandleFailureSwitchAutoMatchmakingPt1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Chaos_Invite_Match.Chaos_Invite_Match_C.HandleFailureSwitchAutoMatchmakingPt2
// (Public, BlueprintCallable, BlueprintEvent)

void UChaos_Invite_Match_C::HandleFailureSwitchAutoMatchmakingPt2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Chaos_Invite_Match_C", "HandleFailureSwitchAutoMatchmakingPt2");

	UObject::ProcessEvent(Func, nullptr);
}

}

