#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConfigKeyAssignMenu

#include "Basic.hpp"

#include "ConfigKeyAssignMenu_classes.hpp"
#include "ConfigKeyAssignMenu_parameters.hpp"


namespace SDK
{

// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.ExecuteUbergraph_ConfigKeyAssignMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::ExecuteUbergraph_ConfigKeyAssignMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "ExecuteUbergraph_ConfigKeyAssignMenu");

	Params::ConfigKeyAssignMenu_C_ExecuteUbergraph_ConfigKeyAssignMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "Tick");

	Params::ConfigKeyAssignMenu_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UConfigKeyAssignMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.AddList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UGamepadSet_C*&             Content                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::AddList(const class UGamepadSet_C*& Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "AddList");

	Params::ConfigKeyAssignMenu_C_AddList Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.GetList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGamepadSet_C**                   Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::GetList(int32 Param_Index_0, class UGamepadSet_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "GetList");

	Params::ConfigKeyAssignMenu_C_GetList Parms{};

	Parms.Param_Index_0 = Param_Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.GetSelectList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGamepadSet_C**                   Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::GetSelectList(class UGamepadSet_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "GetSelectList");

	Params::ConfigKeyAssignMenu_C_GetSelectList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.ActivateList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGamepadSet_C*                    Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::ActivateList(class UGamepadSet_C* Input)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "ActivateList");

	Params::ConfigKeyAssignMenu_C_ActivateList Parms{};

	Parms.Input = Input;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.MoveCursor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Move                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::MoveCursor(int32 Move)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "MoveCursor");

	Params::ConfigKeyAssignMenu_C_MoveCursor Parms{};

	Parms.Move = Move;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetSelectKeyAssign
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfigKeyAssignMenu_C::SetSelectKeyAssign(float ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetSelectKeyAssign");

	Params::ConfigKeyAssignMenu_C_SetSelectKeyAssign Parms{};

	Parms.ID = ID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.Refresh
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.RevertKeybindsToInitialValues
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::RevertKeybindsToInitialValues()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "RevertKeybindsToInitialValues");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.ResetAllKeybinds
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::ResetAllKeybinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "ResetAllKeybinds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.IsChangedKey
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   isEnable                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConfigKeyAssignMenu_C::IsChangedKey(bool* isEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "IsChangedKey");

	Params::ConfigKeyAssignMenu_C_IsChangedKey Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (isEnable != nullptr)
		*isEnable = Parms.isEnable;
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.RefreshInitialKeys
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::RefreshInitialKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "RefreshInitialKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.GetCurrentSelectHelpText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText*                            helpText                                               (Parm, OutParm)

void UConfigKeyAssignMenu_C::GetCurrentSelectHelpText(class FText* helpText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "GetCurrentSelectHelpText");

	Params::ConfigKeyAssignMenu_C_GetCurrentSelectHelpText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (helpText != nullptr)
		*helpText = std::move(Parms.helpText);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetBossRevengeConfig
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetBossRevengeConfig()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetBossRevengeConfig");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetBossRevengeOptions
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetBossRevengeOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetBossRevengeOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetAndrealphusOptions
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetAndrealphusOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetAndrealphusOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetBathinOptions
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetBathinOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetBathinOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetBloodlessOptions
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetBloodlessOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetBloodlessOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetGremoryOptions
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetGremoryOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetGremoryOptions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetClassicConfig
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetClassicConfig()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetClassicConfig");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.SetClassic2Config
// (Public, BlueprintCallable, BlueprintEvent)

void UConfigKeyAssignMenu_C::SetClassic2Config()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "SetClassic2Config");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.UpdateClassic2Config
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnablePlatform                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    EnableDimension                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConfigKeyAssignMenu_C::UpdateClassic2Config(bool EnablePlatform, bool EnableDimension)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "UpdateClassic2Config");

	Params::ConfigKeyAssignMenu_C_UpdateClassic2Config Parms{};

	Parms.EnablePlatform = EnablePlatform;
	Parms.EnableDimension = EnableDimension;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfigKeyAssignMenu.ConfigKeyAssignMenu_C.ShowInputButtons
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UGamepadSet_C*>&           Buff                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UConfigKeyAssignMenu_C::ShowInputButtons(TArray<class UGamepadSet_C*>& Buff)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConfigKeyAssignMenu_C", "ShowInputButtons");

	Params::ConfigKeyAssignMenu_C_ShowInputButtons Parms{};

	Parms.Buff = std::move(Buff);

	UObject::ProcessEvent(Func, &Parms);

	Buff = std::move(Parms.Buff);
}

}

