#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EPB_ExecCommonList

#include "Basic.hpp"


namespace SDK
{

// Enum EPB_ExecCommonList.EPB_ExecCommonList
// NumValues: 0x0008
enum class EPB_ExecCommonList : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator8                           = 5,
	NewEnumerator7                           = 6,
	EPB_MAX                                  = 7,
};

}

