#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Event_Name

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct Event_Name.Event_Name
// 0x0008 (0x0008 - 0x0000)
struct FEvent_Name final
{
public:
	class FName                                   EventID_3_12AD125941995E22959E7BA98E6FDAC2;        // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FEvent_Name;

}

