#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InfomationStatus

#include "Basic.hpp"

#include "InfomationStatus_classes.hpp"
#include "InfomationStatus_parameters.hpp"


namespace SDK
{

// Function InfomationStatus.InfomationStatus_C.SetItemData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPBItemCatalogData&        input_data                                             (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UInfomationStatus_C::SetItemData(const struct FPBItemCatalogData& input_data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InfomationStatus_C", "SetItemData");

	Params::InfomationStatus_C_SetItemData Parms{};

	Parms.input_data = std::move(input_data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InfomationStatus.InfomationStatus_C.UpdateParam
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UInfomationStatus_C::UpdateParam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InfomationStatus_C", "UpdateParam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InfomationStatus.InfomationStatus_C.UpdateAttrivute
// (Public, BlueprintCallable, BlueprintEvent)

void UInfomationStatus_C::UpdateAttrivute()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InfomationStatus_C", "UpdateAttrivute");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InfomationStatus.InfomationStatus_C.GetStatusValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAttackAttribute                        Attrivute_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UInfomationStatus_C::GetStatusValue(EAttackAttribute Attrivute_0, int32* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InfomationStatus_C", "GetStatusValue");

	Params::InfomationStatus_C_GetStatusValue Parms{};

	Parms.Attrivute_0 = Attrivute_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}

}

