#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Int_AnimationNotifyCommon

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "EPB_StartLoopEnd_structs.hpp"


namespace SDK
{

// DynamicClass Int_AnimationNotifyCommon.Int_AnimationNotifyCommon_C
// 0x0000 (0x0000 - 0x0000)
class IInt_AnimationNotifyCommon_C final
{
public:
	void ExecAnimationCommand(class FName bpp__Command__pf, class FName bpp__Value__pf, float bpp__FloatValue__pf, bool* bpp__Ret__pf);
	void ExecAnimationCommandEx(class FName bpp__Command__pf, EPB_StartLoopEnd bpp__Type__pf, bool* bpp__return__pf);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Int_AnimationNotifyCommon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Int_AnimationNotifyCommon_C")
	}
	static class IInt_AnimationNotifyCommon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IInt_AnimationNotifyCommon_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IInt_AnimationNotifyCommon_C;

}

