#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IntArray

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct IntArray.IntArray
// 0x0010 (0x0010 - 0x0000)
struct FIntArray final
{
public:
	TArray<int32>                                 Values_4_617B62C347CC8923F7AD55A402F16CFC;         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FIntArray;

}

