#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lib_Dialogue

#include "Basic.hpp"

#include "Lib_Dialogue_classes.hpp"
#include "Lib_Dialogue_parameters.hpp"


namespace SDK
{

// Function Lib_Dialogue.Lib_Dialogue_C.DialogueBranchMeetsConditions
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__Branch__pf                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp__BranchHost__pf                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FDialogue_TableItem&       bpp__DialogueItem__pf                                  (Parm, NativeAccessSpecifierPublic)
// class ABP_ScriptInterpreter_C*          bpp__ScriptInterpreter__pf                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__ConditionsMet__pf                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::DialogueBranchMeetsConditions(class FName bpp__Branch__pf, class UObject* bpp__BranchHost__pf, const struct FDialogue_TableItem& bpp__DialogueItem__pf, class ABP_ScriptInterpreter_C* bpp__ScriptInterpreter__pf, class UObject* bpp____WorldContext__pf, bool* bpp__ConditionsMet__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "DialogueBranchMeetsConditions");

	Params::Lib_Dialogue_C_DialogueBranchMeetsConditions Parms{};

	Parms.bpp__Branch__pf = bpp__Branch__pf;
	Parms.bpp__BranchHost__pf = bpp__BranchHost__pf;
	Parms.bpp__DialogueItem__pf = std::move(bpp__DialogueItem__pf);
	Parms.bpp__ScriptInterpreter__pf = bpp__ScriptInterpreter__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__ConditionsMet__pf != nullptr)
		*bpp__ConditionsMet__pf = Parms.bpp__ConditionsMet__pf;
}


// Function Lib_Dialogue.Lib_Dialogue_C.ExtractDialogueBranchHost
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    bpp__RawBranch__pf__const                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp__DialoguexResponsexHandler__pfTT                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject**                         bpp__Host__pf                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName*                            bpp__Branch__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::ExtractDialogueBranchHost(const class FString& bpp__RawBranch__pf__const, class UObject* bpp__DialoguexResponsexHandler__pfTT, class UObject* bpp____WorldContext__pf, class UObject** bpp__Host__pf, class FName* bpp__Branch__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "ExtractDialogueBranchHost");

	Params::Lib_Dialogue_C_ExtractDialogueBranchHost Parms{};

	Parms.bpp__RawBranch__pf__const = std::move(bpp__RawBranch__pf__const);
	Parms.bpp__DialoguexResponsexHandler__pfTT = bpp__DialoguexResponsexHandler__pfTT;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Host__pf != nullptr)
		*bpp__Host__pf = Parms.bpp__Host__pf;

	if (bpp__Branch__pf != nullptr)
		*bpp__Branch__pf = Parms.bpp__Branch__pf;
}


// Function Lib_Dialogue.Lib_Dialogue_C.ExtractDialogueTraits
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FDialogue_TableItem&       bpp__Item__pf                                          (Parm, NativeAccessSpecifierPublic)
// class ABP_ScriptInterpreter_C*          bpp__ScriptInterpreter__pf                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class FString>*                  bpp__Traits__pf                                        (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::ExtractDialogueTraits(const struct FDialogue_TableItem& bpp__Item__pf, class ABP_ScriptInterpreter_C* bpp__ScriptInterpreter__pf, class UObject* bpp____WorldContext__pf, TArray<class FString>* bpp__Traits__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "ExtractDialogueTraits");

	Params::Lib_Dialogue_C_ExtractDialogueTraits Parms{};

	Parms.bpp__Item__pf = std::move(bpp__Item__pf);
	Parms.bpp__ScriptInterpreter__pf = bpp__ScriptInterpreter__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Traits__pf != nullptr)
		*bpp__Traits__pf = std::move(Parms.bpp__Traits__pf);
}


// Function Lib_Dialogue.Lib_Dialogue_C.GetDialogueItem
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          bpp__DatatableHost__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__RowName__pf                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogue_TableItem*             bpp__Item__pf                                          (Parm, OutParm, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::GetDialogueItem(class UObject* bpp__DatatableHost__pf, class FName bpp__RowName__pf, class UObject* bpp____WorldContext__pf, struct FDialogue_TableItem* bpp__Item__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "GetDialogueItem");

	Params::Lib_Dialogue_C_GetDialogueItem Parms{};

	Parms.bpp__DatatableHost__pf = bpp__DatatableHost__pf;
	Parms.bpp__RowName__pf = bpp__RowName__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Item__pf != nullptr)
		*bpp__Item__pf = std::move(Parms.bpp__Item__pf);
}


// Function Lib_Dialogue.Lib_Dialogue_C.GetDialogueItem_Func
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          bpp__DatatableHost__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__RowName__pf                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogue_TableItem*             bpp__Item__pf                                          (Parm, OutParm, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::GetDialogueItem_Func(class UObject* bpp__DatatableHost__pf, class FName bpp__RowName__pf, class UObject* bpp____WorldContext__pf, struct FDialogue_TableItem* bpp__Item__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "GetDialogueItem_Func");

	Params::Lib_Dialogue_C_GetDialogueItem_Func Parms{};

	Parms.bpp__DatatableHost__pf = bpp__DatatableHost__pf;
	Parms.bpp__RowName__pf = bpp__RowName__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Item__pf != nullptr)
		*bpp__Item__pf = std::move(Parms.bpp__Item__pf);
}


// Function Lib_Dialogue.Lib_Dialogue_C.GetSpeakerAttributes
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          bpp__DatatableHost__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__SpeakerID__pf                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogueSpeakerAttribute_TableItem*bpp__Attributes__pf                                    (Parm, OutParm, NativeAccessSpecifierPublic)
// bool*                                   bpp__Success__pf                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::GetSpeakerAttributes(class UObject* bpp__DatatableHost__pf, class FName bpp__SpeakerID__pf, class UObject* bpp____WorldContext__pf, struct FDialogueSpeakerAttribute_TableItem* bpp__Attributes__pf, bool* bpp__Success__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "GetSpeakerAttributes");

	Params::Lib_Dialogue_C_GetSpeakerAttributes Parms{};

	Parms.bpp__DatatableHost__pf = bpp__DatatableHost__pf;
	Parms.bpp__SpeakerID__pf = bpp__SpeakerID__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Attributes__pf != nullptr)
		*bpp__Attributes__pf = std::move(Parms.bpp__Attributes__pf);

	if (bpp__Success__pf != nullptr)
		*bpp__Success__pf = Parms.bpp__Success__pf;
}


// Function Lib_Dialogue.Lib_Dialogue_C.GetSpeakerAttributes_Func
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          bpp__DatatableHost__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__SpeakerID__pf                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogueSpeakerAttribute_TableItem*bpp__Attributes__pf                                    (Parm, OutParm, NativeAccessSpecifierPublic)
// bool*                                   bpp__Success__pf                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ULib_Dialogue_C::GetSpeakerAttributes_Func(class UObject* bpp__DatatableHost__pf, class FName bpp__SpeakerID__pf, class UObject* bpp____WorldContext__pf, struct FDialogueSpeakerAttribute_TableItem* bpp__Attributes__pf, bool* bpp__Success__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("Lib_Dialogue_C", "GetSpeakerAttributes_Func");

	Params::Lib_Dialogue_C_GetSpeakerAttributes_Func Parms{};

	Parms.bpp__DatatableHost__pf = bpp__DatatableHost__pf;
	Parms.bpp__SpeakerID__pf = bpp__SpeakerID__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Attributes__pf != nullptr)
		*bpp__Attributes__pf = std::move(Parms.bpp__Attributes__pf);

	if (bpp__Success__pf != nullptr)
		*bpp__Success__pf = Parms.bpp__Success__pf;
}

}

