#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizerSummary

#include "Basic.hpp"

#include "RandomizerSummary_classes.hpp"
#include "RandomizerSummary_parameters.hpp"


namespace SDK
{

// Function RandomizerSummary.RandomizerSummary_C.ExecuteUbergraph_RandomizerSummary
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URandomizerSummary_C::ExecuteUbergraph_RandomizerSummary(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "ExecuteUbergraph_RandomizerSummary");

	Params::RandomizerSummary_C_ExecuteUbergraph_RandomizerSummary Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerSummary.RandomizerSummary_C.OnPressedButton
// (Event, Public, BlueprintEvent)

void URandomizerSummary_C::OnPressedButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "OnPressedButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URandomizerSummary_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "Tick");

	Params::RandomizerSummary_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerSummary.RandomizerSummary_C.Start
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>&OnStepChanged                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
// int32                                   ZOrder                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URandomizerSummary_C::Start(const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>& OnStepChanged, int32 ZOrder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "Start");

	Params::RandomizerSummary_C_Start Parms{};

	Parms.OnStepChanged = OnStepChanged;
	Parms.ZOrder = ZOrder;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerSummary.RandomizerSummary_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void URandomizerSummary_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.WidgetAnimationEvt_close_K2Node_WidgetAnimationEvent_1
// (BlueprintEvent)

void URandomizerSummary_C::WidgetAnimationEvt_close_K2Node_WidgetAnimationEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "WidgetAnimationEvt_close_K2Node_WidgetAnimationEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.WidgetAnimationEvt_open_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void URandomizerSummary_C::WidgetAnimationEvt_open_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "WidgetAnimationEvt_open_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.Initialize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.OnStart
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.OnLoading
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::OnLoading()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "OnLoading");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.OnConfirmPressed
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::OnConfirmPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "OnConfirmPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.OnBackPressed
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::OnBackPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "OnBackPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.SetupText
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::SetupText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "SetupText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerSummary.RandomizerSummary_C.UpdateControlGuide
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerSummary_C::UpdateControlGuide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerSummary_C", "UpdateControlGuide");

	UObject::ProcessEvent(Func, nullptr);
}

}

