#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizerOptions

#include "Basic.hpp"

#include "RandomizerOptions_classes.hpp"
#include "RandomizerOptions_parameters.hpp"


namespace SDK
{

// Function RandomizerOptions.RandomizerOptions_C.ExecuteUbergraph_RandomizerOptions
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URandomizerOptions_C::ExecuteUbergraph_RandomizerOptions(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "ExecuteUbergraph_RandomizerOptions");

	Params::RandomizerOptions_C_ExecuteUbergraph_RandomizerOptions Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerOptions.RandomizerOptions_C.OnPressedButton
// (Event, Public, BlueprintEvent)

void URandomizerOptions_C::OnPressedButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "OnPressedButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URandomizerOptions_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "Tick");

	Params::RandomizerOptions_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerOptions.RandomizerOptions_C.Start
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>&OnStepChanged                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
// int32                                   ZOrder                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URandomizerOptions_C::Start(const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>& OnStepChanged, int32 ZOrder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "Start");

	Params::RandomizerOptions_C_Start Parms{};

	Parms.OnStepChanged = OnStepChanged;
	Parms.ZOrder = ZOrder;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerOptions.RandomizerOptions_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void URandomizerOptions_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.WidgetAnimationEvt_close_K2Node_WidgetAnimationEvent_1
// (BlueprintEvent)

void URandomizerOptions_C::WidgetAnimationEvt_close_K2Node_WidgetAnimationEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "WidgetAnimationEvt_close_K2Node_WidgetAnimationEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.WidgetAnimationEvt_open_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void URandomizerOptions_C::WidgetAnimationEvt_open_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "WidgetAnimationEvt_open_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.OnActive
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::OnActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "OnActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.OnStart
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.SetupLayout
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::SetupLayout()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "SetupLayout");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.MoveSelection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPBUserWidget*                    prev                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPBUserWidget*                    Next                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsLeftRight                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    IsUp                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void URandomizerOptions_C::MoveSelection(class UPBUserWidget* prev, class UPBUserWidget* Next, bool IsLeftRight, bool IsUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "MoveSelection");

	Params::RandomizerOptions_C_MoveSelection Parms{};

	Parms.prev = prev;
	Parms.Next = Next;
	Parms.IsLeftRight = IsLeftRight;
	Parms.IsUp = IsUp;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizerOptions.RandomizerOptions_C.OnContinuePressed
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::OnContinuePressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "OnContinuePressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.SetGameInstanceSettings
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::SetGameInstanceSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "SetGameInstanceSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.SetRandomSeed
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::SetRandomSeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "SetRandomSeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.OnSummaryClosed
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::OnSummaryClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "OnSummaryClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.OnCancelPressed
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::OnCancelPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "OnCancelPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.UpdateControlGuide
// (Public, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::UpdateControlGuide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "UpdateControlGuide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizerOptions.RandomizerOptions_C.UpdateDescriptionText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void URandomizerOptions_C::UpdateDescriptionText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptions_C", "UpdateDescriptionText");

	UObject::ProcessEvent(Func, nullptr);
}

}

