#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SlotSelecterBack

#include "Basic.hpp"


namespace SDK::Params
{

// Function SlotSelecterBack.SlotSelecterBack_C.ExecuteUbergraph_SlotSelecterBack
// 0x0004 (0x0004 - 0x0000)
struct SlotSelecterBack_C_ExecuteUbergraph_SlotSelecterBack final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SlotSelecterBack_C_ExecuteUbergraph_SlotSelecterBack;

// Function SlotSelecterBack.SlotSelecterBack_C.SetDispBG
// 0x0001 (0x0001 - 0x0000)
struct SlotSelecterBack_C_SetDispBG final
{
public:
	bool                                          is_disp;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_SlotSelecterBack_C_SetDispBG;

}

