#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Step_N2004

#include "Basic.hpp"

#include "EPB_PlayerInfoVectorType_structs.hpp"
#include "Engine_structs.hpp"
#include "EPB_PlayerStance_structs.hpp"
#include "ESubSubStep_structs.hpp"
#include "ProjectBlood_structs.hpp"
#include "ProjectBlood_classes.hpp"
#include "EPB_PlayerCtr_FloatParameterType_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Step_N2004_Action_structs.hpp"
#include "EPB_P0000_GunDamageType_structs.hpp"
#include "EPB_PlayerInfoBoolType_structs.hpp"
#include "ESubStep_structs.hpp"
#include "EPB_AttackStance_structs.hpp"
#include "EPB_ActionRequestCategory_structs.hpp"
#include "EPB_N1011_EnchantType_structs.hpp"
#include "EPB_ExecCommandType_structs.hpp"


namespace SDK
{

// DynamicClass Step_N2004.Step_N2004_C
// 0x06E8 (0x0D40 - 0x0658)
class UStep_N2004_C final : public UPBStepBase
{
public:
	uint8                                         Pad_658[0x8];                                      // 0x0658(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStepUpdateMoveInfo                    MoveInfo;                                          // 0x0660(0x0094)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                Velocity;                                          // 0x06F4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveTime;                                          // 0x0700(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DeltaSeconds;                                      // 0x0704(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         IdelWaitTime;                                      // 0x0708(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_70C[0x4];                                      // 0x070C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 Prob_Temp;                                         // 0x0710(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<int32>                                 ActionMax;                                         // 0x0720(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<int32>                                 ActionCounter;                                     // 0x0730(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FVector                                JumpVelocity;                                      // 0x0740(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         JumpCount;                                         // 0x074C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       InitStep;                                          // 0x0750(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_751[0x3];                                      // 0x0751(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                ForwardMoveVelocity;                               // 0x0754(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BackMoveVelocity;                                  // 0x0760(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DashTime;                                          // 0x076C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       TurnAfterStep;                                     // 0x0770(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_771[0x3];                                      // 0x0771(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         JumpKickAcc;                                       // 0x0774(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SlidingBrakeRate;                                  // 0x0778(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         JumpKickVelocity;                                  // 0x077C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EscapeTime;                                        // 0x0780(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         UniqueTime;                                        // 0x0784(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TotalWeight;                                       // 0x0788(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CurrentWeight;                                     // 0x078C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AngryTime;                                         // 0x0790(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Level;                                             // 0x0794(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                TargetLocation;                                    // 0x0798(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EStep_N2004_Action                            ActionType;                                        // 0x07A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7A5[0x3];                                      // 0x07A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<bool>                                  CanAction;                                         // 0x07A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	float                                         EnemyDistance;                                     // 0x07B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DamageCounter;                                     // 0x07BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NormalModeTimer;                                   // 0x07C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DistanceType;                                      // 0x07C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsJumpKick;                                        // 0x07C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7C9[0x7];                                      // 0x07C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        JumpTarget;                                        // 0x07D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	class UCurveFloat*                            OffsetCurwve;                                      // 0x07E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         UniqueCounter;                                     // 0x07E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         EscapeStep;                                        // 0x07EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EscapeCounter;                                     // 0x07F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7F4[0x4];                                      // 0x07F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AChr_N2004_C*                           N2004;                                             // 0x07F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UOBJ_CameraManager_C*                   EventCam;                                          // 0x0800(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CanBreakCrystal;                                   // 0x0808(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CanDropShard;                                      // 0x0809(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsHard;                                            // 0x080A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_80B[0x5];                                      // 0x080B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UPBVirtualController*                   VirCon;                                            // 0x0810(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APBRoomVolume*                          RoomVolume;                                        // 0x0818(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OldSubStep;                                        // 0x0820(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NewSubStep;                                        // 0x0824(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_Step3;                                // 0x0828(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_829[0x3];                                      // 0x0829(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds2;                        // 0x082C(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FWorldResult                           K2Node_Event_HitResult1;                           // 0x0830(0x0130)(Transient, DuplicateTransient, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	EMovementMode                                 K2Node_Event_OldMovementMode1;                     // 0x0960(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMovementMode                                 K2Node_Event_NewMovementMode1;                     // 0x0961(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0962(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_Step2;                                // 0x0963(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         K2Node_Event_DeltaSeconds1;                        // 0x0964(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FWorldResult                           K2Node_Event_HitResult;                            // 0x0968(0x0130)(Transient, DuplicateTransient, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	EMovementMode                                 K2Node_Event_OldMovementMode;                      // 0x0A98(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMovementMode                                 K2Node_Event_NewMovementMode;                      // 0x0A99(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_Step1;                                // 0x0A9A(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A9B[0x1];                                      // 0x0A9B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0A9C(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FStepDamageInfo                        K2Node_Event_DamageInfo;                           // 0x0AA0(0x00E0)(Transient, DuplicateTransient, NoDestructor, NativeAccessSpecifierPublic)
	struct FPBET_OverlapPCInfo                    K2Node_Event_OverlapPCInfo1;                       // 0x0B80(0x0038)(Transient, DuplicateTransient, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FPBET_OverlapPCInfo                    K2Node_Event_OverlapPCInfo;                        // 0x0BB8(0x0038)(Transient, DuplicateTransient, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FStepNotifyInfo                        K2Node_Event_info;                                 // 0x0BF0(0x0018)(Transient, DuplicateTransient, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0C08(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_OldStep1;                             // 0x0C09(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_NewStep;                              // 0x0C0A(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_OldStep;                              // 0x0C0B(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         K2Node_Event_OldSubStep1;                          // 0x0C0C(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         K2Node_Event_NewSubStep1;                          // 0x0C10(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchEnum1_CmpSuccess;                     // 0x0C14(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0C15(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0C16(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPBStep                                       K2Node_Event_Step;                                 // 0x0C17(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         K2Node_Event_OldSubStep;                           // 0x0C18(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         K2Node_Event_NewSubStep;                           // 0x0C1C(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger1_CmpSuccess;                  // 0x0C20(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchEnum2_CmpSuccess;                     // 0x0C21(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger2_CmpSuccess;                  // 0x0C22(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger3_CmpSuccess;                  // 0x0C23(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger4_CmpSuccess;                  // 0x0C24(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C25[0x3];                                      // 0x0C25(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_Can_Move_hitResult;                       // 0x0C28(0x0088)(Transient, DuplicateTransient, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FHitResult                             CallFunc_Can_Move_hitResult1;                      // 0x0CB0(0x0088)(Transient, DuplicateTransient, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger5_CmpSuccess;                  // 0x0D38(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger6_CmpSuccess;                  // 0x0D39(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          K2Node_SwitchInteger7_CmpSuccess;                  // 0x0D3A(0x0001)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D3B[0x5];                                      // 0x0D3B(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void CalcDistanceToEnemy(float* bpp__Distance__pf);
	void CalcMove(const struct FVector& bpp__Spline__pf, struct FVector* bpp__Move__pf);
	bool Can_Move(float bpp__Distance__pf, bool bpp__IsxForward__pfT, struct FHitResult* bpp__hitResult__pf);
	void CheckActionTypeCrouch(EStep_N2004_Action bpp__ActionType__pf, bool bpp__EnemyCrouch__pf, EStep_N2004_Action* bpp__Action__pf);
	void CnvNotRootMotion(const struct FStepUpdateInputMovement& bpp__InMoveInfo__pf, struct FStepUpdateInputMovement* bpp__OutMoveInfo__pf);
	void CorrectionProbTemp(int32 bpp__Movex__pfT, int32 bpp__Jump__pf, int32 bpp__DoubleJump__pf, int32 bpp__DoubleJumpKick__pf, int32 bpp__Kick__pf, int32 bpp__Genocide__pf, int32 bpp__DashSobut__pf, int32 bpp__Homing__pf);
	void GetEnemyVector(struct FVector* bpp__Vector__pf);
	void IsEnemyFront(bool* bpp__Front__pf);
	void IsExtraBossMode(bool* bpp__IsExtraBossMode__pf);
	bool IsFalling();
	void IsInner3D(const struct FVector& bpp__Position1__pf, const struct FVector& bpp__Position2__pf, float bpp__Distance__pf, bool* bpp__IsInner__pf);
	void JumpToTarget(const struct FVector& bpp__JumpTargetLocation__pf, int32 bpp__ProbxBackxJump__pfTT);
	void NormalizationJumpVelocity(const struct FVector& bpp__JumpVelocity__pf, struct FVector* bpp__Result__pf);
	void NormalJumpVelcity(const struct FVector& bpp__JumpTargetLocation__pf);
	void OnDamaged(EPBStep bpp__Step__pf, float bpp__DeltaSeconds__pf, const struct FStepDamageInfo& bpp__DamageInfo__pf__const);
	void OnPBETOverlapEndPCBox(const struct FPBET_OverlapPCInfo& bpp__OverlapPCInfo__pf__const);
	void OnPBETOverlapPCBox(const struct FPBET_OverlapPCInfo& bpp__OverlapPCInfo__pf__const);
	void PlayerCtr_AccelWorld(bool bpp__Stop__pf, bool* bpp__return__pf);
	void PlayerCtr_BookClose(bool* bpp__return__pf);
	void PlayerCtr_EndFacialAnimation(bool* bpp__return__pf);
	void PlayerCtr_EventDealDamageInfo(class FName bpp__DamageID__pf, bool bpp__IsHit__pf, EPBBloodColor bpp__BloodColor__pf, float bpp__DamageValue__pf, class APBBaseCharacter* bpp__ChrIns__pf, const struct FVector& bpp__HitWorldLocation__pf, bool bpp__IsCritical__pf, bool bpp__IsBullet__pf, class FName bpp__HitBone__pf, EAttackAttribute bpp__EffectiveAttribute__pf, class UPBCollisionObject* bpp__AttackCollision__pf, bool* bpp__return__pf);
	void PlayerCtr_ExecChairDamamage(bool* bpp__return__pf);
	void PlayerCtr_ExecCommand(EPB_ExecCommandType bpp__CommandType__pf, bool bpp__BoolParameter__pf, float bpp__FloatParameter__pf, int32 bpp__IntParameter__pf, const struct FVector& bpp__VectorPrameter__pf, class FName bpp__NameParameter__pf, bool* bpp__return__pf);
	void PlayerCtr_FlipRequest(bool bpp__IsRight__pf, bool* bpp__return__pf);
	void PlayerCtr_GetDirectionalHandWorldLocation(struct FVector* bpp__WorldLocation__pf);
	void PlayerCtr_GetForwardVector(struct FVector* bpp__WorldDirection__pf);
	void PlayerCtr_GetTriggerHandWorldLocation(struct FVector* bpp__WorldLocation__pf);
	void PlayerCtr_JumpAttackLateralMoveReverse(bool bpp__Value__pf, bool* bpp__return__pf);
	void PlayerCtr_JumpkickOff(bool* bpp__return__pf);
	void PlayerCtr_LaunchGun(class FName bpp__BulletID__pf, class FName bpp__SocketName__pf, bool bpp__IsArts__pf, bool* bpp__IsLaunch__pf, class APBBulletActor** bpp__BulletInstance__pf);
	void PlayerCtr_PlayShardVoice(EShardType bpp__ShardType__pf, bool* bpp__return__pf);
	void PlayerCtr_ReleaseInvert(float bpp__Distance__pf, const struct FVector& bpp__Dir__pf, bool bpp__IsDamageIfNotInvert__pf, bool* bpp__return__pf);
	void PlayerCtr_RequestEnchant(bool bpp__Request__pf, bool bpp__ForceEnchantType__pf, EPB_N1011_EnchantType bpp__EnchantType__pf, bool* bpp__return__pf);
	void PlayerCtr_SetActionRequestCondition(EPB_ActionRequestCategory bpp__ActionRequestCategory__pf, bool* bpp__return__pf);
	void PlayerCtr_SetAimEffectCondition(class FName bpp__ShardID__pf, bool* bpp__return__pf);
	void PlayerCtr_SetAnimBool(EAnimBoolArray bpp__AnimBoolType__pf, bool bpp__Value__pf, bool* bpp__return__pf);
	void PlayerCtr_SetBoolParameter(EPB_PlayerInfoBoolType bpp__ParameterType__pf, bool bpp__ParameterValue__pf, bool* bpp__return__pf);
	void PlayerCtr_SetChairMagicRecoverRate(float bpp__MagicRecoverSpeedRate__pf, bool* bpp__return__pf);
	void PlayerCtr_SetDefaultBrakeRate(float bpp__BrakeRate__pf, bool* bpp__return__pf);
	void PlayerCtr_SetDirectionalShardEnable(bool bpp__Enable__pf, bool* bpp__return__pf);
	void PlayerCtr_SetDisenableStandUpChairByeKey(bool* bpp__return__pf);
	void PlayerCtr_SetEquipEnchantParameter(ECarriedCatalog bpp__EquipType__pf, bool bpp__IsUnEquip__pf, bool* bpp__return__pf);
	void PlayerCtr_SetEquipMeshVisible(bool bpp__CapVisible__pf, bool bpp__HeadVisible__pf, bool bpp__Accesarry1Visible__pf, bool bpp__Accesarry2Visible__pf, bool bpp__MufflerVisible__pf, bool bpp__HairVisible__pf, bool* bpp__return__pf);
	void PlayerCtr_SetEventAttack(bool* bpp__return__pf);
	void PlayerCtr_SetFakeMoonWarpSetting(const struct FVector& bpp__WarpTargetLocation__pf, bool* bpp__return__pf);
	void PlayerCtr_SetFloatParameter(EPB_PlayerCtr_FloatParameterType bpp__ParameterType__pf, float bpp__ParameterValue__pf, bool* bpp__return__pf);
	void PlayerCtr_SetIsInnerBloodPool(bool bpp__IsInner__pf, bool* bpp__return__pf);
	void PlayerCtr_SetMirroringReverse(bool bpp__Reverse__pf, bool* bpp__return__pf);
	void PlayerCtr_SetReflectionMaxDistance(float bpp__MaxDistance__pf, bool* bpp__return__pf);
	void PlayerCtr_SetShardBulletActor(EShardType bpp__ShardType__pf, class APBBulletActor** bpp__BulleIns__pf, bool* bpp__return__pf);
	void PlayerCtr_SetShardEnchantParameter(class FName bpp__ShardID__pf, bool bpp__IsUnEquip__pf, int32 bpp__Rank__pf, bool* bpp__return__pf);
	void PlayerCtr_SetSnapShot(const struct FPoseSnapshot& bpp__SnapShot__pf, bool* bpp__return__pf);
	void PlayerCtr_SetUseEmissive(bool bpp__Use__pf, float bpp__FlashDuration__pf, const struct FVector& bpp__EmissiveColor__pf, int32 bpp__Priority__pf, float bpp__EmissiveMin__pf, float bpp__EmissiveMax__pf, float bpp__EmissiveContrast__pf, float bpp__Duration__pf, bool* bpp__return__pf);
	void PlayerCtr_SetWaterFallSpeedRate(float bpp__VerticalSpeedRate__pf, float bpp__HorizontalSpeedRate__pf, bool* bpp__return__pf);
	void PlayerCtr_SpawnBullet(class FName bpp__BulletID__pf, const struct FVector& bpp__SpawnWorldLocation__pf, const struct FVector& bpp__TargetWorldLocation__pf, EBulletDirection bpp__DirectionType__pf, ECarriedCatalog bpp__SpawnerType__pf, bool bpp__IsOverRoom__pf, class FName bpp__ShardID__pf, bool* bpp__IsSpawn__pf, class APBBulletActor** bpp__BulletIns__pf, class AActor** bpp__BulletSubActor__pf);
	void PlayerCtr_SpawnBulletEx(class FName bpp__BulletID__pf, const struct FPBBulletParameter& bpp__BulletParamter__pf, const struct FPBBallisticParameter& bpp__BallisticParameter__pf, const struct FVector& bpp__SpawnWorldLocation__pf, const struct FVector& bpp__TargetWorldLocation__pf, EBulletDirection bpp__DirectionType__pf, ECarriedCatalog bpp__SpawnerType__pf, bool bpp__IsOverRoom__pf, class FName bpp__ShardID__pf, bool* bpp__IsSpawn__pf, class APBBulletActor** bpp__BulletIns__pf, class AActor** bpp__BulletSubActor__pf);
	void PlayerCtr_SpawnEffect(class FName bpp__EffectID__pf, const struct FVector& bpp__SpawnWorldLocation__pf, float bpp__Scale__pf, float bpp__TimeDilation__pf, const struct FVector& bpp__RotationVector__pf, ECarriedCatalog bpp__SpawnType__pf, bool* bpp__IsSpawn__pf, class APBParticle** bpp__EffectInstance__pf, class UParticleSystemComponent** bpp__ParticleSystemComponent__pf);
	void PlayerCtr_SpawnWeaponTrail(class FName bpp__SocketName__pf, EPB_AttackStance bpp__StanceType__pf, bool* bpp__return__pf);
	void PlayerCtr_StandUpFromChair(bool* bpp__return__pf);
	void PlayerCtr_StartBookRead(bool* bpp__return__pf);
	void PlayerCtr_StartFacialAnimation(EPBFacialExpression bpp__FacialType__pf, bool* bpp__return__pf);
	void PlayerCtr_TransForceStep(EStepEntry bpp__WildCard__pf, EPBStep bpp__MainStep__pf, ESubStep bpp__SubStep__pf, ESubSubStep bpp__SubSubStep__pf, bool* bpp__return__pf);
	void PlayerCtr_UpdateMasteryAttackRate(class FName bpp__WeaponID__pf, bool bpp__IsCheckShard__pf, class FName bpp__ShardID__pf, bool bpp__IsEquip__pf, bool* bpp__return__pf);
	void PlayerCtr_WarpRequest(const struct FVector& bpp__WorldLocation__pf, struct FVector* bpp__return__pf);
	void PlayerInfo_GetActionRequestManager(class UOBJ_ActionRequest_C** bpp__ActReqMan__pf);
	void PlayerInfo_GetAimDirectionVector(bool* bpp__IsAiming__pf, struct FVector* bpp__WorldVector__pf);
	void PlayerInfo_GetAimDirectionWorldVector(struct FVector* bpp__WorldVector__pf);
	void PlayerInfo_GetAimRotation(struct FRotator* bpp__Rotation__pf);
	void PlayerInfo_GetBoolValue(EPB_PlayerInfoBoolType bpp__Type__pf, bool* bpp__return__pf);
	void PlayerInfo_GetBulletInfo(int32* bpp__ConsumeNum__pf, float* bpp__DamageRate__pf, class FName* bpp__DamageMasterID__pf, bool* bpp__IsNotConsume__pf, bool* bpp__IsHoming__pf, EPB_P0000_GunDamageType* bpp__DamageType__pf);
	void PlayerInfo_GetEquipActor(ECarriedCatalog bpp__EquipType__pf, class AEQBP_Root_C** bpp__EquipActor__pf, bool* bpp__IsValid__pf);
	void PlayerInfo_GetEquipItemID(ECarriedCatalog bpp__EquipType__pf, bool bpp__IsPrevEquip__pf, class FName* bpp__ItemId__pf);
	void PlayerInfo_GetEquipModelActor(EPBEquipModelType bpp__Type__pf, class AActor** bpp__EquipActor__pf);
	void PlayerInfo_GetEquipSpecialAttribute(EPBEquipSpecialAttribute bpp__Type__pf, bool bpp__IsRate__pf, float* bpp__Value__pf);
	void PlayerInfo_GetPlayerAttackInfo(EWeaponType* bpp__WeaponType__pf, EPB_PlayerStance* bpp__PlayerStance__pf, bool* bpp__IsSlant__pf);
	void PlayerInfo_GetPlayerSpeed(struct FVector* bpp__CharacterSpeed__pf);
	void PlayerInfo_GetShardBulletActor(EShardType bpp__ShardType__pf, class APBBulletActor** bpp__ShardBulletIns__pf);
	void PlayerInfo_GetShardInfo(class FName bpp__ShardID__pf, EShardType bpp__ShardType__pf, bool* bpp__IsEquip__pf, bool* bpp__IsPossess__pf, int32* bpp__Rank__pf, float* bpp__RankVakue__pf, int32* bpp__Grade__pf, float* bpp__GradeValue__pf);
	void PlayerInfo_GetVectorValue(EPB_PlayerInfoVectorType bpp__Type__pf, struct FVector* bpp__Vector__pf);
	void PlayerInfo_GetWorldLocationRecord(int32 bpp__Index__pf, struct FVector* bpp__WorldLocation__pf);
	void PlayerInfo_IsDispWeapon(bool* bpp__IsDisp__pf);
	void PlayerInfo_IsEnableAreaDoor(bool* bpp__IsEnable__pf);
	void PlayerInfo_SetAccelWorldSelf(bool bpp__IsAccelWorlding__pf, bool* bpp__return__pf);
	void PlayerInfo_SetEquipSpecialAttribute(EPBEquipSpecialAttribute bpp__Type__pf, float bpp__Value__pf, bool* bpp__return__pf);
	bool ProbabilityOfSuccess(int32 bpp__Probabilityxofxsuccess__pfTT);
	void ProbJumpDir(struct FVector* bpp__NewParam__pf, int32 bpp__BackJumpxProb__pfT, struct FVector* bpp__Result__pf);
	void ProbUpdate(EStep_N2004_Action bpp__AvtionType__pf);
	void SetProbTempElem(EStep_N2004_Action bpp__Index__pf, int32 bpp__AdjustmentxValue__pfT);
	void Set_Can_Action(EStep_N2004_Action bpp__ActionxType__pfT, bool bpp__CanxAction__pfT);
	bool TurnAndToNextStep(EPBStep bpp__NextStep__pf);
	void UpdateAttack1(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateAttack2(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateAttack3(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateAttack4(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateAttack5(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateDamaged1(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateDash(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateDeath1(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateEvent(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateFall(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateIdle(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateInit(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateJump1(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateLand(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateMove(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdatePostStep(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdatePreStep(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateThinkPattern();
	void UpdateTurn(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateUnique1(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);
	void UpdateUnique2(float bpp__DeltaSeconds__pf, const struct FStepUpdateMoveInfo& bpp__MoveInfo__pf__const, struct FStepUpdateOutput* bpp__Output__pf);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Step_N2004_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Step_N2004_C")
	}
	static class UStep_N2004_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStep_N2004_C>();
	}
};
DUMPER7_ASSERTS_UStep_N2004_C;

}

