#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ArchiveAchivementWindow

#include "Basic.hpp"

#include "ArchiveAchivementWindow_classes.hpp"
#include "ArchiveAchivementWindow_parameters.hpp"


namespace SDK
{

// Function ArchiveAchivementWindow.ArchiveAchivementWindow_C.ExecuteUbergraph_ArchiveAchivementWindow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UArchiveAchivementWindow_C::ExecuteUbergraph_ArchiveAchivementWindow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveAchivementWindow_C", "ExecuteUbergraph_ArchiveAchivementWindow");

	Params::ArchiveAchivementWindow_C_ExecuteUbergraph_ArchiveAchivementWindow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ArchiveAchivementWindow.ArchiveAchivementWindow_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UArchiveAchivementWindow_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveAchivementWindow_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ArchiveAchivementWindow.ArchiveAchivementWindow_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UArchiveAchivementWindow_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ArchiveAchivementWindow_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}

}

