#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DM_BaseLantern

#include "Basic.hpp"

#include "BP_DM_BaseLantern_classes.hpp"
#include "BP_DM_BaseLantern_parameters.hpp"


namespace SDK
{

// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BndEvt__DamagedSphere2_K2Node_ComponentBoundEvent_1_PBETDelegate_OnDamaged__DelegateSignature
// (Native, Public, HasOutParams)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf__const                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BndEvt__DamagedSphere2_K2Node_ComponentBoundEvent_1_PBETDelegate_OnDamaged__DelegateSignature(const struct FPBET_DamageInfo& bpp__DamageInfo__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BndEvt__DamagedSphere2_K2Node_ComponentBoundEvent_1_PBETDelegate_OnDamaged__DelegateSignature");

	Params::BP_DM_BaseLantern_C_BndEvt__DamagedSphere2_K2Node_ComponentBoundEvent_1_PBETDelegate_OnDamaged__DelegateSignature Parms{};

	Parms.bpp__DamageInfo__pf__const = std::move(bpp__DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BndEvt__DamagedSphere3_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature
// (Native, Public, HasOutParams)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf__const                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BndEvt__DamagedSphere3_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature(const struct FPBET_DamageInfo& bpp__DamageInfo__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BndEvt__DamagedSphere3_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature");

	Params::BP_DM_BaseLantern_C_BndEvt__DamagedSphere3_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature Parms{};

	Parms.bpp__DamageInfo__pf__const = std::move(bpp__DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BndEvt__DamagedSphere4_K2Node_ComponentBoundEvent_2_PBETDelegate_OnDamaged__DelegateSignature
// (Native, Public, HasOutParams)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf__const                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BndEvt__DamagedSphere4_K2Node_ComponentBoundEvent_2_PBETDelegate_OnDamaged__DelegateSignature(const struct FPBET_DamageInfo& bpp__DamageInfo__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BndEvt__DamagedSphere4_K2Node_ComponentBoundEvent_2_PBETDelegate_OnDamaged__DelegateSignature");

	Params::BP_DM_BaseLantern_C_BndEvt__DamagedSphere4_K2Node_ComponentBoundEvent_2_PBETDelegate_OnDamaged__DelegateSignature Parms{};

	Parms.bpp__DamageInfo__pf__const = std::move(bpp__DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BndEvt__DamagedSphere5_K2Node_ComponentBoundEvent_3_PBETDelegate_OnDamaged__DelegateSignature
// (Native, Public, HasOutParams)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf__const                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BndEvt__DamagedSphere5_K2Node_ComponentBoundEvent_3_PBETDelegate_OnDamaged__DelegateSignature(const struct FPBET_DamageInfo& bpp__DamageInfo__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BndEvt__DamagedSphere5_K2Node_ComponentBoundEvent_3_PBETDelegate_OnDamaged__DelegateSignature");

	Params::BP_DM_BaseLantern_C_BndEvt__DamagedSphere5_K2Node_ComponentBoundEvent_3_PBETDelegate_OnDamaged__DelegateSignature Parms{};

	Parms.bpp__DamageInfo__pf__const = std::move(bpp__DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BndEvt__DamagedSphere6_K2Node_ComponentBoundEvent_4_PBETDelegate_OnDamaged__DelegateSignature
// (Native, Public, HasOutParams)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf__const                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BndEvt__DamagedSphere6_K2Node_ComponentBoundEvent_4_PBETDelegate_OnDamaged__DelegateSignature(const struct FPBET_DamageInfo& bpp__DamageInfo__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BndEvt__DamagedSphere6_K2Node_ComponentBoundEvent_4_PBETDelegate_OnDamaged__DelegateSignature");

	Params::BP_DM_BaseLantern_C_BndEvt__DamagedSphere6_K2Node_ComponentBoundEvent_4_PBETDelegate_OnDamaged__DelegateSignature Parms{};

	Parms.bpp__DamageInfo__pf__const = std::move(bpp__DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BndEvt__DamageSphere_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature
// (Native, Public, HasOutParams)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf__const                             (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BndEvt__DamageSphere_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature(const struct FPBET_DamageInfo& bpp__DamageInfo__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BndEvt__DamageSphere_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature");

	Params::BP_DM_BaseLantern_C_BndEvt__DamageSphere_K2Node_ComponentBoundEvent_0_PBETDelegate_OnDamaged__DelegateSignature Parms{};

	Parms.bpp__DamageInfo__pf__const = std::move(bpp__DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.BreakeLantern
// (Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FVector&                   bpp__Dir__pf                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   bpp__Location__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   bpp__Damage__pf                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   bpp__Impulse__pf                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::BreakeLantern(const struct FVector& bpp__Dir__pf, const struct FVector& bpp__Location__pf, float bpp__Damage__pf, float bpp__Impulse__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "BreakeLantern");

	Params::BP_DM_BaseLantern_C_BreakeLantern Parms{};

	Parms.bpp__Dir__pf = std::move(bpp__Dir__pf);
	Parms.bpp__Location__pf = std::move(bpp__Location__pf);
	Parms.bpp__Damage__pf = bpp__Damage__pf;
	Parms.bpp__Impulse__pf = bpp__Impulse__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.CanAttackDestroyLantern
// (Native, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf                                    (Parm, NativeAccessSpecifierPublic)
// bool*                                   bpp__CanBreak__pf                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::CanAttackDestroyLantern(const struct FPBET_DamageInfo& bpp__DamageInfo__pf, bool* bpp__CanBreak__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "CanAttackDestroyLantern");

	Params::BP_DM_BaseLantern_C_CanAttackDestroyLantern Parms{};

	Parms.bpp__DamageInfo__pf = std::move(bpp__DamageInfo__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__CanBreak__pf != nullptr)
		*bpp__CanBreak__pf = Parms.bpp__CanBreak__pf;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.CanDamageLanternCheck
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class APBBaseCharacter*                 bpp__BaseCaracter__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__CanDamageLantern__pf                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::CanDamageLanternCheck(class APBBaseCharacter* bpp__BaseCaracter__pf, bool* bpp__CanDamageLantern__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "CanDamageLanternCheck");

	Params::BP_DM_BaseLantern_C_CanDamageLanternCheck Parms{};

	Parms.bpp__BaseCaracter__pf = bpp__BaseCaracter__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__CanDamageLantern__pf != nullptr)
		*bpp__CanDamageLantern__pf = Parms.bpp__CanDamageLantern__pf;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.DestroyLantern
// (Net, NetReliable, Native, Event, NetMulticast, Public, BlueprintCallable)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf                                    (Parm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::DestroyLantern(const struct FPBET_DamageInfo& bpp__DamageInfo__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "DestroyLantern");

	Params::BP_DM_BaseLantern_C_DestroyLantern Parms{};

	Parms.bpp__DamageInfo__pf = std::move(bpp__DamageInfo__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.DestroyNotUseComponent
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::DestroyNotUseComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "DestroyNotUseComponent");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.DestroyStaticMesh
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::DestroyStaticMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "DestroyStaticMesh");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.DMFade
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::DMFade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "DMFade");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.DMHiddenInGame
// (Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bpp__IsHidden__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::DMHiddenInGame(bool bpp__IsHidden__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "DMHiddenInGame");

	Params::BP_DM_BaseLantern_C_DMHiddenInGame Parms{};

	Parms.bpp__IsHidden__pf = bpp__IsHidden__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.fadeOut2__FinishedFunc
// (Native, Public)

void ABP_DM_BaseLantern_C::fadeOut2__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "fadeOut2__FinishedFunc");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.fadeOut2__UpdateFunc
// (Native, Public)

void ABP_DM_BaseLantern_C::fadeOut2__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "fadeOut2__UpdateFunc");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.fadeOut__FinishedFunc
// (Native, Public)

void ABP_DM_BaseLantern_C::fadeOut__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "fadeOut__FinishedFunc");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.fadeOut__UpdateFunc
// (Native, Public)

void ABP_DM_BaseLantern_C::fadeOut__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "fadeOut__UpdateFunc");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.GetDamageInfo
// (Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__PBET_DamageInfo__pf__const                        (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// struct FVector*                         bpp__Dir__pf                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector*                         bpp__Location__pf                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float*                                  bpp__DamageAmount__pf                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float*                                  bpp__Impulse__pf                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::GetDamageInfo(const struct FPBET_DamageInfo& bpp__PBET_DamageInfo__pf__const, struct FVector* bpp__Dir__pf, struct FVector* bpp__Location__pf, float* bpp__DamageAmount__pf, float* bpp__Impulse__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "GetDamageInfo");

	Params::BP_DM_BaseLantern_C_GetDamageInfo Parms{};

	Parms.bpp__PBET_DamageInfo__pf__const = std::move(bpp__PBET_DamageInfo__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Dir__pf != nullptr)
		*bpp__Dir__pf = std::move(Parms.bpp__Dir__pf);

	if (bpp__Location__pf != nullptr)
		*bpp__Location__pf = std::move(Parms.bpp__Location__pf);

	if (bpp__DamageAmount__pf != nullptr)
		*bpp__DamageAmount__pf = Parms.bpp__DamageAmount__pf;

	if (bpp__Impulse__pf != nullptr)
		*bpp__Impulse__pf = Parms.bpp__Impulse__pf;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.LanternBreakDeleteComponent
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::LanternBreakDeleteComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "LanternBreakDeleteComponent");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.LanternDropOffset
// (Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure)
// Parameters:
// struct FVector*                         bpp__Offset__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector*                         bpp__SplineDir__pf                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::LanternDropOffset(struct FVector* bpp__Offset__pf, struct FVector* bpp__SplineDir__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "LanternDropOffset");

	Params::BP_DM_BaseLantern_C_LanternDropOffset Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Offset__pf != nullptr)
		*bpp__Offset__pf = std::move(Parms.bpp__Offset__pf);

	if (bpp__SplineDir__pf != nullptr)
		*bpp__SplineDir__pf = std::move(Parms.bpp__SplineDir__pf);
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.OnChangeOutScreenPaused
// (Native, Event, Public)
// Parameters:
// bool                                    bpp__bPaused__pf                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::OnChangeOutScreenPaused(bool bpp__bPaused__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "OnChangeOutScreenPaused");

	Params::BP_DM_BaseLantern_C_OnChangeOutScreenPaused Parms{};

	Parms.bpp__bPaused__pf = bpp__bPaused__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.OnDamageOverlap
// (Native, Public, BlueprintCallable)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__PBET_DamageInfo__pf                               (Parm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::OnDamageOverlap(const struct FPBET_DamageInfo& bpp__PBET_DamageInfo__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "OnDamageOverlap");

	Params::BP_DM_BaseLantern_C_OnDamageOverlap Parms{};

	Parms.bpp__PBET_DamageInfo__pf = std::move(bpp__PBET_DamageInfo__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.OnDestroyLantern
// (Native, Public, BlueprintCallable)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__DamageInfo__pf                                    (Parm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::OnDestroyLantern(const struct FPBET_DamageInfo& bpp__DamageInfo__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "OnDestroyLantern");

	Params::BP_DM_BaseLantern_C_OnDestroyLantern Parms{};

	Parms.bpp__DamageInfo__pf = std::move(bpp__DamageInfo__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.OnReceiveEvent
// (Native, Event, Public)
// Parameters:
// class APBEventListenerManager*          bpp__eventManager__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__eventKey__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__eventSubKey__pf                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp__eventSender__pf                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::OnReceiveEvent(class APBEventListenerManager* bpp__eventManager__pf, class FName bpp__eventKey__pf, class FName bpp__eventSubKey__pf, class UObject* bpp__eventSender__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "OnReceiveEvent");

	Params::BP_DM_BaseLantern_C_OnReceiveEvent Parms{};

	Parms.bpp__eventManager__pf = bpp__eventManager__pf;
	Parms.bpp__eventKey__pf = bpp__eventKey__pf;
	Parms.bpp__eventSubKey__pf = bpp__eventSubKey__pf;
	Parms.bpp__eventSender__pf = bpp__eventSender__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.RandomizerGetKeyFromMap
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__RandomizedxShard__pfT                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName*                            bpp__ActualxShard__pfT                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::RandomizerGetKeyFromMap(class FName bpp__RandomizedxShard__pfT, class FName* bpp__ActualxShard__pfT)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "RandomizerGetKeyFromMap");

	Params::BP_DM_BaseLantern_C_RandomizerGetKeyFromMap Parms{};

	Parms.bpp__RandomizedxShard__pfT = bpp__RandomizedxShard__pfT;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__ActualxShard__pfT != nullptr)
		*bpp__ActualxShard__pfT = Parms.bpp__ActualxShard__pfT;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.ReceiveBeginPlay
// (Native, Event, Public)

void ABP_DM_BaseLantern_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.ReceiveTick
// (Native, Event, Public)
// Parameters:
// float                                   bpp__DeltaSeconds__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::ReceiveTick(float bpp__DeltaSeconds__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "ReceiveTick");

	Params::BP_DM_BaseLantern_C_ReceiveTick Parms{};

	Parms.bpp__DeltaSeconds__pf = bpp__DeltaSeconds__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.SetAttacker
// (Native, Public, BlueprintCallable)
// Parameters:
// const struct FPBET_DamageInfo&          bpp__Info__pf                                          (Parm, NativeAccessSpecifierPublic)

void ABP_DM_BaseLantern_C::SetAttacker(const struct FPBET_DamageInfo& bpp__Info__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "SetAttacker");

	Params::BP_DM_BaseLantern_C_SetAttacker Parms{};

	Parms.bpp__Info__pf = std::move(bpp__Info__pf);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.SetDMMID
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::SetDMMID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "SetDMMID");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.SpawnEffect
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::SpawnEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "SpawnEffect");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.SpawnItem
// (Native, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::SpawnItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "SpawnItem");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.SwingLantarn__FinishedFunc
// (Native, Public)

void ABP_DM_BaseLantern_C::SwingLantarn__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "SwingLantarn__FinishedFunc");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.SwingLantarn__UpdateFunc
// (Native, Public)

void ABP_DM_BaseLantern_C::SwingLantarn__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "SwingLantarn__UpdateFunc");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_DM_BaseLantern.BP_DM_BaseLantern_C.UserConstructionScript
// (Native, Event, Public, BlueprintCallable)

void ABP_DM_BaseLantern_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DM_BaseLantern_C", "UserConstructionScript");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

