#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_Dialogue

#include "Basic.hpp"

#include "BPC_Dialogue_classes.hpp"
#include "BPC_Dialogue_parameters.hpp"


namespace SDK
{

// Function BPC_Dialogue.BPC_Dialogue_C.ChangeHost
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          bpp__NewHost__pf                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__BranchName__pf                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__Success__pf                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::ChangeHost(class UObject* bpp__NewHost__pf, class FName bpp__BranchName__pf, class APlayerController* bpp__PC__pf, bool* bpp__Success__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "ChangeHost");

	Params::BPC_Dialogue_C_ChangeHost Parms{};

	Parms.bpp__NewHost__pf = bpp__NewHost__pf;
	Parms.bpp__BranchName__pf = bpp__BranchName__pf;
	Parms.bpp__PC__pf = bpp__PC__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Success__pf != nullptr)
		*bpp__Success__pf = Parms.bpp__Success__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.Clear
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// bool*                                   bpp__ClearxFailed__pfT                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::Clear(bool* bpp__ClearxFailed__pfT)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "Clear");

	Params::BPC_Dialogue_C_Clear Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__ClearxFailed__pfT != nullptr)
		*bpp__ClearxFailed__pfT = Parms.bpp__ClearxFailed__pfT;
}


// Function BPC_Dialogue.BPC_Dialogue_C.ClearUseConditions
// (Native, Public, BlueprintCallable)

void UBPC_Dialogue_C::ClearUseConditions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "ClearUseConditions");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.DisplayUI
// (Native, Public, BlueprintCallable)
// Parameters:
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::DisplayUI(class APlayerController* bpp__PC__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "DisplayUI");

	Params::BPC_Dialogue_C_DisplayUI Parms{};

	Parms.bpp__PC__pf = bpp__PC__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.ExecuteUbergraph_BPC_Dialogue_1
// (Final, Native, Public)
// Parameters:
// int32                                   bpp__EntryPoint__pf                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::ExecuteUbergraph_BPC_Dialogue_1(int32 bpp__EntryPoint__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "ExecuteUbergraph_BPC_Dialogue_1");

	Params::BPC_Dialogue_C_ExecuteUbergraph_BPC_Dialogue_1 Parms{};

	Parms.bpp__EntryPoint__pf = bpp__EntryPoint__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.Exit
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// bool                                    bpp__ExitSelfOnly__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__ExitxFailed__pfT                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::Exit(bool bpp__ExitSelfOnly__pf, bool* bpp__ExitxFailed__pfT)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "Exit");

	Params::BPC_Dialogue_C_Exit Parms{};

	Parms.bpp__ExitSelfOnly__pf = bpp__ExitSelfOnly__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__ExitxFailed__pfT != nullptr)
		*bpp__ExitxFailed__pfT = Parms.bpp__ExitxFailed__pfT;
}


// Function BPC_Dialogue.BPC_Dialogue_C.ExtractDialogueBranchHost
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    bpp__RawBranch__pf__const                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject**                         bpp__Host__pf                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName*                            bpp__Branch__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::ExtractDialogueBranchHost(const class FString& bpp__RawBranch__pf__const, class UObject** bpp__Host__pf, class FName* bpp__Branch__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "ExtractDialogueBranchHost");

	Params::BPC_Dialogue_C_ExtractDialogueBranchHost Parms{};

	Parms.bpp__RawBranch__pf__const = std::move(bpp__RawBranch__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Host__pf != nullptr)
		*bpp__Host__pf = Parms.bpp__Host__pf;

	if (bpp__Branch__pf != nullptr)
		*bpp__Branch__pf = Parms.bpp__Branch__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.FormatError_AssetNotFoundOrInvalid
// (Native, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const class FString&                    bpp__AssetName__pf__const                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__funcName__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          bpp__Result__pf                                        (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::FormatError_AssetNotFoundOrInvalid(const class FString& bpp__AssetName__pf__const, class FName bpp__funcName__pf, class FString* bpp__Result__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "FormatError_AssetNotFoundOrInvalid");

	Params::BPC_Dialogue_C_FormatError_AssetNotFoundOrInvalid Parms{};

	Parms.bpp__AssetName__pf__const = std::move(bpp__AssetName__pf__const);
	Parms.bpp__funcName__pf = bpp__funcName__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Result__pf != nullptr)
		*bpp__Result__pf = std::move(Parms.bpp__Result__pf);
}


// Function BPC_Dialogue.BPC_Dialogue_C.FormatError_MissingArg
// (Native, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const class FString&                    bpp__argName__pf__const                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__funcName__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   bpp__ArgNumber__pf                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          bpp__Result__pf                                        (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::FormatError_MissingArg(const class FString& bpp__argName__pf__const, class FName bpp__funcName__pf, int32 bpp__ArgNumber__pf, class FString* bpp__Result__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "FormatError_MissingArg");

	Params::BPC_Dialogue_C_FormatError_MissingArg Parms{};

	Parms.bpp__argName__pf__const = std::move(bpp__argName__pf__const);
	Parms.bpp__funcName__pf = bpp__funcName__pf;
	Parms.bpp__ArgNumber__pf = bpp__ArgNumber__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Result__pf != nullptr)
		*bpp__Result__pf = std::move(Parms.bpp__Result__pf);
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetActualInputType
// (Native, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// EDialogueInputType                      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EDialogueInputType UBPC_Dialogue_C::GetActualInputType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetActualInputType");

	Params::BPC_Dialogue_C_GetActualInputType Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetAsset
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__ItemName__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FNamedAsset*                     bpp__AssetReference__pf                                (Parm, OutParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetAsset(class FName bpp__ItemName__pf, struct FNamedAsset* bpp__AssetReference__pf, bool* bpp__Found__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetAsset");

	Params::BPC_Dialogue_C_GetAsset Parms{};

	Parms.bpp__ItemName__pf = bpp__ItemName__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__AssetReference__pf != nullptr)
		*bpp__AssetReference__pf = std::move(Parms.bpp__AssetReference__pf);

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetDialogueItem
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__ItemName__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogue_TableItem*             bpp__Item__pf                                          (Parm, OutParm, NativeAccessSpecifierPublic)
// bool*                                   bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetDialogueItem(class FName bpp__ItemName__pf, struct FDialogue_TableItem* bpp__Item__pf, bool* bpp__Found__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetDialogueItem");

	Params::BPC_Dialogue_C_GetDialogueItem Parms{};

	Parms.bpp__ItemName__pf = bpp__ItemName__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Item__pf != nullptr)
		*bpp__Item__pf = std::move(Parms.bpp__Item__pf);

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetDialogueItem_Func
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__ItemName__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogue_TableItem*             bpp__Item__pf                                          (Parm, OutParm, NativeAccessSpecifierPublic)
// bool*                                   bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetDialogueItem_Func(class FName bpp__ItemName__pf, struct FDialogue_TableItem* bpp__Item__pf, bool* bpp__Found__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetDialogueItem_Func");

	Params::BPC_Dialogue_C_GetDialogueItem_Func Parms{};

	Parms.bpp__ItemName__pf = bpp__ItemName__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Item__pf != nullptr)
		*bpp__Item__pf = std::move(Parms.bpp__Item__pf);

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetDialogueRowNames
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TArray<class FName>*                    bpp__Names__pf                                         (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetDialogueRowNames(TArray<class FName>* bpp__Names__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetDialogueRowNames");

	Params::BPC_Dialogue_C_GetDialogueRowNames Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Names__pf != nullptr)
		*bpp__Names__pf = std::move(Parms.bpp__Names__pf);
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetDialogueRowNames_Func
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// TArray<class FName>*                    bpp__Names__pf                                         (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetDialogueRowNames_Func(TArray<class FName>* bpp__Names__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetDialogueRowNames_Func");

	Params::BPC_Dialogue_C_GetDialogueRowNames_Func Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Names__pf != nullptr)
		*bpp__Names__pf = std::move(Parms.bpp__Names__pf);
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetNextState
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__RequestState__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName*                            bpp__Flow__pf                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetNextState(class FName bpp__RequestState__pf, class FName* bpp__Flow__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetNextState");

	Params::BPC_Dialogue_C_GetNextState Parms{};

	Parms.bpp__RequestState__pf = bpp__RequestState__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Flow__pf != nullptr)
		*bpp__Flow__pf = Parms.bpp__Flow__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetScriptInterpreter
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class ABP_ScriptInterpreter_C**         bpp__Interpreter__pf                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetScriptInterpreter(class ABP_ScriptInterpreter_C** bpp__Interpreter__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetScriptInterpreter");

	Params::BPC_Dialogue_C_GetScriptInterpreter Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Interpreter__pf != nullptr)
		*bpp__Interpreter__pf = Parms.bpp__Interpreter__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetScriptInterpreter_Func
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class ABP_ScriptInterpreter_C**         bpp__Interpreter__pf                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetScriptInterpreter_Func(class ABP_ScriptInterpreter_C** bpp__Interpreter__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetScriptInterpreter_Func");

	Params::BPC_Dialogue_C_GetScriptInterpreter_Func Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Interpreter__pf != nullptr)
		*bpp__Interpreter__pf = Parms.bpp__Interpreter__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetSpeakerAttributes
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__SpeakerID__pf                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogueSpeakerAttribute_TableItem*bpp__Result__pf                                        (Parm, OutParm, NativeAccessSpecifierPublic)
// bool*                                   bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetSpeakerAttributes(class FName bpp__SpeakerID__pf, struct FDialogueSpeakerAttribute_TableItem* bpp__Result__pf, bool* bpp__Found__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetSpeakerAttributes");

	Params::BPC_Dialogue_C_GetSpeakerAttributes Parms{};

	Parms.bpp__SpeakerID__pf = bpp__SpeakerID__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Result__pf != nullptr)
		*bpp__Result__pf = std::move(Parms.bpp__Result__pf);

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetSpeakerAttributes_Func
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__SpeakerID__pf                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FDialogueSpeakerAttribute_TableItem*bpp__Result__pf                                        (Parm, OutParm, NativeAccessSpecifierPublic)
// bool*                                   bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetSpeakerAttributes_Func(class FName bpp__SpeakerID__pf, struct FDialogueSpeakerAttribute_TableItem* bpp__Result__pf, bool* bpp__Found__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetSpeakerAttributes_Func");

	Params::BPC_Dialogue_C_GetSpeakerAttributes_Func Parms{};

	Parms.bpp__SpeakerID__pf = bpp__SpeakerID__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Result__pf != nullptr)
		*bpp__Result__pf = std::move(Parms.bpp__Result__pf);

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.GetUseCondition
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    bpp__Key__pf__const                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          bpp__ConditionString__pf                               (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32*                                  bpp__Index__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::GetUseCondition(const class FString& bpp__Key__pf__const, class FString* bpp__ConditionString__pf, bool* bpp__Found__pf, int32* bpp__Index__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "GetUseCondition");

	Params::BPC_Dialogue_C_GetUseCondition Parms{};

	Parms.bpp__Key__pf__const = std::move(bpp__Key__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__ConditionString__pf != nullptr)
		*bpp__ConditionString__pf = std::move(Parms.bpp__ConditionString__pf);

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;

	if (bpp__Index__pf != nullptr)
		*bpp__Index__pf = Parms.bpp__Index__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.HandleScriptFunction
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__Function__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class FString>*                  bpp__Args__pf                                          (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
// class FString*                          bpp__Result__pf                                        (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::HandleScriptFunction(class FName bpp__Function__pf, TArray<class FString>* bpp__Args__pf, class FString* bpp__Result__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "HandleScriptFunction");

	Params::BPC_Dialogue_C_HandleScriptFunction Parms{};

	Parms.bpp__Function__pf = bpp__Function__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Args__pf != nullptr)
		*bpp__Args__pf = std::move(Parms.bpp__Args__pf);

	if (bpp__Result__pf != nullptr)
		*bpp__Result__pf = std::move(Parms.bpp__Result__pf);
}


// Function BPC_Dialogue.BPC_Dialogue_C.HandleScriptFunction_Func
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__Function__pf                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class FString>*                  bpp__Args__pf                                          (Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
// class FString*                          bpp__Result__pf                                        (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::HandleScriptFunction_Func(class FName bpp__Function__pf, TArray<class FString>* bpp__Args__pf, class FString* bpp__Result__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "HandleScriptFunction_Func");

	Params::BPC_Dialogue_C_HandleScriptFunction_Func Parms{};

	Parms.bpp__Function__pf = bpp__Function__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Args__pf != nullptr)
		*bpp__Args__pf = std::move(Parms.bpp__Args__pf);

	if (bpp__Result__pf != nullptr)
		*bpp__Result__pf = std::move(Parms.bpp__Result__pf);
}


// Function BPC_Dialogue.BPC_Dialogue_C.IsTopicActive
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// bool*                                   bpp__Active__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::IsTopicActive(bool* bpp__Active__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "IsTopicActive");

	Params::BPC_Dialogue_C_IsTopicActive Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Active__pf != nullptr)
		*bpp__Active__pf = Parms.bpp__Active__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.OnAllTextDisplayed
// (Native, Public, BlueprintCallable)

void UBPC_Dialogue_C::OnAllTextDisplayed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "OnAllTextDisplayed");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.OnReceiveResponse
// (Native, Event, Public, HasOutParams, BlueprintCallable)
// Parameters:
// int32                                   bpp__ResponseIdx__pf                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__BranchName__pf                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp__BranchHost__pf                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__Failed__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::OnReceiveResponse(int32 bpp__ResponseIdx__pf, class FName bpp__BranchName__pf, class UObject* bpp__BranchHost__pf, class APlayerController* bpp__PC__pf, bool* bpp__Failed__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "OnReceiveResponse");

	Params::BPC_Dialogue_C_OnReceiveResponse Parms{};

	Parms.bpp__ResponseIdx__pf = bpp__ResponseIdx__pf;
	Parms.bpp__BranchName__pf = bpp__BranchName__pf;
	Parms.bpp__BranchHost__pf = bpp__BranchHost__pf;
	Parms.bpp__PC__pf = bpp__PC__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Failed__pf != nullptr)
		*bpp__Failed__pf = Parms.bpp__Failed__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.OnSkip
// (Native, Public, BlueprintCallable)

void UBPC_Dialogue_C::OnSkip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "OnSkip");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.OnStateChanged
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__To__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             bpp__From__pf                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__ValidToProcess__pf                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::OnStateChanged(class FName bpp__To__pf, class FName bpp__From__pf, class APlayerController* bpp__PC__pf, bool* bpp__ValidToProcess__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "OnStateChanged");

	Params::BPC_Dialogue_C_OnStateChanged Parms{};

	Parms.bpp__To__pf = bpp__To__pf;
	Parms.bpp__From__pf = bpp__From__pf;
	Parms.bpp__PC__pf = bpp__PC__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__ValidToProcess__pf != nullptr)
		*bpp__ValidToProcess__pf = Parms.bpp__ValidToProcess__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.ParseStateName
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__FullStateName__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName*                            bpp__BranchName__pf                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32*                                  bpp__PartNumber__pf                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::ParseStateName(class FName bpp__FullStateName__pf, class FName* bpp__BranchName__pf, int32* bpp__PartNumber__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "ParseStateName");

	Params::BPC_Dialogue_C_ParseStateName Parms{};

	Parms.bpp__FullStateName__pf = bpp__FullStateName__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__BranchName__pf != nullptr)
		*bpp__BranchName__pf = Parms.bpp__BranchName__pf;

	if (bpp__PartNumber__pf != nullptr)
		*bpp__PartNumber__pf = Parms.bpp__PartNumber__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.PopPreviousState
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName*                            bpp__Found__pf                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::PopPreviousState(class FName* bpp__Found__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "PopPreviousState");

	Params::BPC_Dialogue_C_PopPreviousState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__Found__pf != nullptr)
		*bpp__Found__pf = Parms.bpp__Found__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.ReceiveTick
// (Native, Event, Public)
// Parameters:
// float                                   bpp__DeltaSeconds__pf                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::ReceiveTick(float bpp__DeltaSeconds__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "ReceiveTick");

	Params::BPC_Dialogue_C_ReceiveTick Parms{};

	Parms.bpp__DeltaSeconds__pf = bpp__DeltaSeconds__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.RemoveUseCondition
// (Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    bpp__Key__pf__const                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::RemoveUseCondition(const class FString& bpp__Key__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "RemoveUseCondition");

	Params::BPC_Dialogue_C_RemoveUseCondition Parms{};

	Parms.bpp__Key__pf__const = std::move(bpp__Key__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.SetInputType
// (Native, Public, BlueprintCallable)
// Parameters:
// EDialogueInputType                      bpp__Type__pf                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__ForceUpdate__pf                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::SetInputType(EDialogueInputType bpp__Type__pf, bool bpp__ForceUpdate__pf, class APlayerController* bpp__PC__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "SetInputType");

	Params::BPC_Dialogue_C_SetInputType Parms{};

	Parms.bpp__Type__pf = bpp__Type__pf;
	Parms.bpp__ForceUpdate__pf = bpp__ForceUpdate__pf;
	Parms.bpp__PC__pf = bpp__PC__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.SetSkipDialogue
// (Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bpp__DoSkip__pf                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::SetSkipDialogue(bool bpp__DoSkip__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "SetSkipDialogue");

	Params::BPC_Dialogue_C_SetSkipDialogue Parms{};

	Parms.bpp__DoSkip__pf = bpp__DoSkip__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.SetState
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__NewxFlow__pfT                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__Force__pf                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__IgnoreCurrentStateInHistory__pf                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__NewParam__pf                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::SetState(class FName bpp__NewxFlow__pfT, bool bpp__Force__pf, class APlayerController* bpp__PC__pf, bool bpp__IgnoreCurrentStateInHistory__pf, bool* bpp__NewParam__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "SetState");

	Params::BPC_Dialogue_C_SetState Parms{};

	Parms.bpp__NewxFlow__pfT = bpp__NewxFlow__pfT;
	Parms.bpp__Force__pf = bpp__Force__pf;
	Parms.bpp__PC__pf = bpp__PC__pf;
	Parms.bpp__IgnoreCurrentStateInHistory__pf = bpp__IgnoreCurrentStateInHistory__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__NewParam__pf != nullptr)
		*bpp__NewParam__pf = Parms.bpp__NewParam__pf;
}


// Function BPC_Dialogue.BPC_Dialogue_C.SetUseCondition
// (Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    bpp__Key__pf__const                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    bpp__Condition__pf__const                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::SetUseCondition(const class FString& bpp__Key__pf__const, const class FString& bpp__Condition__pf__const)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "SetUseCondition");

	Params::BPC_Dialogue_C_SetUseCondition Parms{};

	Parms.bpp__Key__pf__const = std::move(bpp__Key__pf__const);
	Parms.bpp__Condition__pf__const = std::move(bpp__Condition__pf__const);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BPC_Dialogue.BPC_Dialogue_C.Use_Func
// (Native, Public, BlueprintCallable)
// Parameters:
// class APlayerController*                bpp__PC__pf                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UBPC_Dialogue_C::Use_Func(class APlayerController* bpp__PC__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_Dialogue_C", "Use_Func");

	Params::BPC_Dialogue_C_Use_Func Parms{};

	Parms.bpp__PC__pf = bpp__PC__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

