#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cmp_SensorControler

#include "Basic.hpp"

#include "Struct_Rectangle_structs.hpp"
#include "Cmp_Root_classes.hpp"


namespace SDK
{

// DynamicClass Cmp_SensorControler.Cmp_SensorControler_C
// 0x0048 (0x0298 - 0x0250)
class UCmp_SensorControler_C final : public UCmp_Root_C
{
public:
	TArray<struct FStruct_Rectangle>              Rectangle;                                         // 0x0250(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	int32                                         Size;                                              // 0x0260(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Temp_int_Variable;                                 // 0x0264(0x0004)(ZeroConstructor, Transient, DuplicateTransient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FStruct_Rectangle                      K2Node_MakeStruct_Struct_Rectangle;                // 0x0268(0x0030)(Transient, DuplicateTransient, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void DebugIsInner(int32 bpp__actionId__pf, int32 bpp__actionIdToDebug__pf, bool bpp__isInnerSuccessful__pf, float bpp__Radius__pf, const struct FVector& bpp__Position__pf, class UPBStepBase* bpp__Step__pf, class APBBaseCharacter* bpp__baseChr__pf, float bpp__boxWidth__pf, float bpp__boxHeight__pf, class APBBaseCharacter* bpp__targetChr__pf);
	void DrawSensor();
	void DrawSensorEX(int32 bpp__ID__pf, const struct FLinearColor& bpp__Color__pf);
	void DrawSensorEX_WithScale(int32 bpp__ID__pf, const struct FLinearColor& bpp__Color__pf, float bpp__ScaleWidth__pf, float bpp__ScaleHeight__pf);
	void GetAllSeonsor(TArray<struct FStruct_Rectangle>* bpp__Sensors__pf);
	void GetFreeIndex(int32 bpp__ID__pf, int32* bpp__Index__pf);
	void GetPosition(const struct FVector& bpp__Position__pf, struct FVector* bpp__Value__pf);
	void GetProcessTime(int32 bpp__ID__pf, float* bpp__Time__pf);
	void GetSensor(int32 bpp__ID__pf, bool* bpp__IsSuccess__pf, struct FStruct_Rectangle* bpp__Sensor__pf, int32* bpp__Index__pf);
	void GetSensorWithExec(int32 bpp__ID__pf, bool* bpp__IsSuccess__pf, struct FStruct_Rectangle* bpp__Sensor__pf, int32* bpp__Index__pf);
	void IsInner(int32 bpp__ID__pf, class APBBaseCharacter* bpp__Target__pf, float bpp__Radius__pf, bool* bpp__IsIn__pf);
	void IsInnerEx(int32 bpp__ID__pf, const struct FVector& bpp__Target__pf, float bpp__Radius__pf, const struct FVector& bpp__SpeedVector__pf, float bpp__Rate__pf, bool* bpp__IsIn__pf);
	void IsInnerForActiveSencor(int32 bpp__ID__pf, class APBBaseCharacter* bpp__Target__pf, bool* bpp__IsIn__pf);
	void IsInnerHomingLocation(int32 bpp__ID__pf, class APBBaseCharacter* bpp__Target__pf, float bpp__Radius__pf, bool* bpp__IsIn__pf);
	void IsInRectangle(const struct FVector& bpp__Point__pf, const struct FVector& bpp__Center__pf, float bpp__Width__pf, float bpp__Height__pf, bool* bpp__IsIn__pf);
	void IsInRectangleForSpline(const struct FVector& bpp__Point__pf, const struct FVector& bpp__Center__pf, float bpp__Width__pf, float bpp__Height__pf, bool* bpp__IsIn__pf);
	void SetBufferSize(int32 bpp__Size__pf);
	void SetSensor(int32 bpp__ID__pf, float bpp__Width__pf, float bpp__Height__pf, const struct FVector& bpp__Offset__pf, bool* bpp__IsSuccess__pf);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("Cmp_SensorControler_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Cmp_SensorControler_C")
	}
	static class UCmp_SensorControler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCmp_SensorControler_C>();
	}
};
DUMPER7_ASSERTS_UCmp_SensorControler_C;

}

