#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonAttrivuteIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ProjectBlood_structs.hpp"
#include "ProjectBlood_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CommonAttrivuteIcon.CommonAttrivuteIcon_C
// 0x0018 (0x0270 - 0x0258)
class UCommonAttrivuteIcon_C final : public UPBUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 icon;                                              // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EAttackAttribute                              IconID;                                            // 0x0268(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CommonAttrivuteIcon(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Initialize();
	void Setup();
	void SetIconImage(EAttackAttribute Index_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CommonAttrivuteIcon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CommonAttrivuteIcon_C")
	}
	static class UCommonAttrivuteIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommonAttrivuteIcon_C>();
	}
};
DUMPER7_ASSERTS_UCommonAttrivuteIcon_C;

}

