#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonMenuListWindow

#include "Basic.hpp"

#include "CommonMenuListWindow_classes.hpp"
#include "CommonMenuListWindow_parameters.hpp"


namespace SDK
{

// Function CommonMenuListWindow.CommonMenuListWindow_C.ExecuteUbergraph_CommonMenuListWindow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::ExecuteUbergraph_CommonMenuListWindow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "ExecuteUbergraph_CommonMenuListWindow");

	Params::CommonMenuListWindow_C_ExecuteUbergraph_CommonMenuListWindow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.BndEvt__ScrollView_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   CurrentOffset                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::BndEvt__ScrollView_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature(float CurrentOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "BndEvt__ScrollView_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature");

	Params::CommonMenuListWindow_C_BndEvt__ScrollView_K2Node_ComponentBoundEvent_0_OnUserScrolledEvent__DelegateSignature Parms{};

	Parms.CurrentOffset = CurrentOffset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "Tick");

	Params::CommonMenuListWindow_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCommonMenuListWindow_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCommonMenuListWindow_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "PreConstruct");

	Params::CommonMenuListWindow_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.IsEnableListItem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   isEnable                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCommonMenuListWindow_C::IsEnableListItem(bool* isEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "IsEnableListItem");

	Params::CommonMenuListWindow_C_IsEnableListItem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (isEnable != nullptr)
		*isEnable = Parms.isEnable;
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.Clean
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::Clean()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "Clean");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.AddList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Param_Index_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemListItem_C**                 retItem                                                (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::AddList(int32* Param_Index_0, class UItemListItem_C** retItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "AddList");

	Params::CommonMenuListWindow_C_AddList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Index_0 != nullptr)
		*Param_Index_0 = Parms.Param_Index_0;

	if (retItem != nullptr)
		*retItem = Parms.retItem;
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.GetList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemListItem_C**                 ret                                                    (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::GetList(int32 Param_Index_0, class UItemListItem_C** ret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "GetList");

	Params::CommonMenuListWindow_C_GetList Parms{};

	Parms.Param_Index_0 = Param_Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (ret != nullptr)
		*ret = Parms.ret;
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.GetSelectList
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UItemListItem_C**                 ret                                                    (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::GetSelectList(class UItemListItem_C** ret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "GetSelectList");

	Params::CommonMenuListWindow_C_GetSelectList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ret != nullptr)
		*ret = Parms.ret;
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.UpdateLast
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::UpdateLast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "UpdateLast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.UpdateScroll
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::UpdateScroll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "UpdateScroll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.SetMenuCursor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::SetMenuCursor(int32 Param_Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "SetMenuCursor");

	Params::CommonMenuListWindow_C_SetMenuCursor Parms{};

	Parms.Param_Index_0 = Param_Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.MoveMenuCursor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MoveVal                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UItemListItem_C**                 Description                                            (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::MoveMenuCursor(int32 MoveVal, class UItemListItem_C** Description)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "MoveMenuCursor");

	Params::CommonMenuListWindow_C_MoveMenuCursor Parms{};

	Parms.MoveVal = MoveVal;

	UObject::ProcessEvent(Func, &Parms);

	if (Description != nullptr)
		*Description = Parms.Description;
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.ResetScrollOffset
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::ResetScrollOffset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "ResetScrollOffset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.UpdateScrollOffset
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::UpdateScrollOffset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "UpdateScrollOffset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.SetListIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCommonMenuListWindow_C::SetListIndex(int32 Param_Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "SetListIndex");

	Params::CommonMenuListWindow_C_SetListIndex Parms{};

	Parms.Param_Index_0 = Param_Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.ResetInternalScroll
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::ResetInternalScroll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "ResetInternalScroll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.ClampListIndex
// (Public, BlueprintCallable, BlueprintEvent)

void UCommonMenuListWindow_C::ClampListIndex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "ClampListIndex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CommonMenuListWindow.CommonMenuListWindow_C.IsListEmpty
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsListEmpty_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCommonMenuListWindow_C::IsListEmpty(bool* IsListEmpty_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonMenuListWindow_C", "IsListEmpty");

	Params::CommonMenuListWindow_C_IsListEmpty Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsListEmpty_0 != nullptr)
		*IsListEmpty_0 = Parms.IsListEmpty_0;
}

}

