#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DialogueCaptureCameraShake

#include "Basic.hpp"

#include "ProjectBlood_classes.hpp"


namespace SDK
{

// DynamicClass DialogueCaptureCameraShake.DialogueCaptureCameraShake_C
// 0x0000 (0x0170 - 0x0170)
class UDialogueCaptureCameraShake_C final : public UPBDialogueCameraShake
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("DialogueCaptureCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DialogueCaptureCameraShake_C")
	}
	static class UDialogueCaptureCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDialogueCaptureCameraShake_C>();
	}
};
DUMPER7_ASSERTS_UDialogueCaptureCameraShake_C;

}

