#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DLCInstance_0004

#include "Basic.hpp"


namespace SDK::Params
{

// Function DLCInstance_0004.DLCInstance_0004_C.OnSystemSaveLoaded
// 0x0001 (0x0001 - 0x0000)
struct DLCInstance_0004_C_OnSystemSaveLoaded final
{
public:
	bool                                          bpp__DLCAvailable__pf;                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DLCInstance_0004_C_OnSystemSaveLoaded;

}

