#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventManagerWrapper

#include "Basic.hpp"

#include "EventManagerWrapper_classes.hpp"
#include "EventManagerWrapper_parameters.hpp"


namespace SDK
{

// Function EventManagerWrapper.EventManagerWrapper_C.BeginEvent+
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class FName                             bpp__AxEventxID__pfTT                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__UsexSkipxFade__pfTT                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__PreventxRoomxBGM__pfTT                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EPBResetInvertType                      bpp__InvertType__pf                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__IsResetChangeBunny__pf                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__IsResetShovelArmor__pf                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__IsResetStep__pf                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UEventManagerWrapper_C::BeginEvent_(class FName bpp__AxEventxID__pfTT, bool bpp__UsexSkipxFade__pfTT, bool bpp__PreventxRoomxBGM__pfTT, EPBResetInvertType bpp__InvertType__pf, bool bpp__IsResetChangeBunny__pf, bool bpp__IsResetShovelArmor__pf, bool bpp__IsResetStep__pf, class UObject* bpp____WorldContext__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EventManagerWrapper_C", "BeginEvent+");

	Params::EventManagerWrapper_C_BeginEvent_ Parms{};

	Parms.bpp__AxEventxID__pfTT = bpp__AxEventxID__pfTT;
	Parms.bpp__UsexSkipxFade__pfTT = bpp__UsexSkipxFade__pfTT;
	Parms.bpp__PreventxRoomxBGM__pfTT = bpp__PreventxRoomxBGM__pfTT;
	Parms.bpp__InvertType__pf = bpp__InvertType__pf;
	Parms.bpp__IsResetChangeBunny__pf = bpp__IsResetChangeBunny__pf;
	Parms.bpp__IsResetShovelArmor__pf = bpp__IsResetShovelArmor__pf;
	Parms.bpp__IsResetStep__pf = bpp__IsResetStep__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function EventManagerWrapper.EventManagerWrapper_C.EndEvent+
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FName                             bpp__EventID__pf                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__ParentRoomBGM__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__IsChangeBunny__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bpp__IsShovelArmor__pf                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UObject*                          bpp____WorldContext__pf                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bpp__return__pf                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UEventManagerWrapper_C::EndEvent_(class FName bpp__EventID__pf, bool bpp__ParentRoomBGM__pf, bool bpp__IsChangeBunny__pf, bool bpp__IsShovelArmor__pf, class UObject* bpp____WorldContext__pf, bool* bpp__return__pf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EventManagerWrapper_C", "EndEvent+");

	Params::EventManagerWrapper_C_EndEvent_ Parms{};

	Parms.bpp__EventID__pf = bpp__EventID__pf;
	Parms.bpp__ParentRoomBGM__pf = bpp__ParentRoomBGM__pf;
	Parms.bpp__IsChangeBunny__pf = bpp__IsChangeBunny__pf;
	Parms.bpp__IsShovelArmor__pf = bpp__IsShovelArmor__pf;
	Parms.bpp____WorldContext__pf = bpp____WorldContext__pf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bpp__return__pf != nullptr)
		*bpp__return__pf = Parms.bpp__return__pf;
}

}

