#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBST_GearSEVolume

#include "Basic.hpp"


namespace SDK
{

// ScriptStruct PBST_GearSEVolume.PBST_GearSEVolume
// 0x000C (0x000C - 0x0000)
struct FPBST_GearSEVolume final
{
public:
	class FName                                   LevelID_21_5795CED9461952F0964F7DAE24DCB6C9;       // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SoundVolumeRate_23_6DC14F1044C77F3267CF998408BF24E0; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FPBST_GearSEVolume;

}

