#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBWorldCollisionInRoomBP

#include "Basic.hpp"

#include "PBWorldCollisionInRoomBP_classes.hpp"


namespace SDK
{

// Function PBWorldCollisionInRoomBP.PBWorldCollisionInRoomBP_C.ReceiveBeginPlay
// (Native, Event, Public)

void APBWorldCollisionInRoomBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PBWorldCollisionInRoomBP_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PBWorldCollisionInRoomBP.PBWorldCollisionInRoomBP_C.UserConstructionScript
// (Native, Event, Public, BlueprintCallable)

void APBWorldCollisionInRoomBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PBWorldCollisionInRoomBP_C", "UserConstructionScript");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

