#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizerOptionDescription

#include "Basic.hpp"

#include "RandomizerOptionDescription_classes.hpp"
#include "RandomizerOptionDescription_parameters.hpp"


namespace SDK
{

// Function RandomizerOptionDescription.RandomizerOptionDescription_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void URandomizerOptionDescription_C::SetText(const class FText& text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomizerOptionDescription_C", "SetText");

	Params::RandomizerOptionDescription_C_SetText Parms{};

	Parms.text = std::move(text);

	UObject::ProcessEvent(Func, &Parms);
}

}

