#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SlotSelecterBack

#include "Basic.hpp"

#include "SlotSelecterBack_classes.hpp"
#include "SlotSelecterBack_parameters.hpp"


namespace SDK
{

// Function SlotSelecterBack.SlotSelecterBack_C.ExecuteUbergraph_SlotSelecterBack
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USlotSelecterBack_C::ExecuteUbergraph_SlotSelecterBack(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SlotSelecterBack_C", "ExecuteUbergraph_SlotSelecterBack");

	Params::SlotSelecterBack_C_ExecuteUbergraph_SlotSelecterBack Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SlotSelecterBack.SlotSelecterBack_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USlotSelecterBack_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SlotSelecterBack_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SlotSelecterBack.SlotSelecterBack_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void USlotSelecterBack_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SlotSelecterBack_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SlotSelecterBack.SlotSelecterBack_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void USlotSelecterBack_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SlotSelecterBack_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SlotSelecterBack.SlotSelecterBack_C.SetDispBG
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    is_disp                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USlotSelecterBack_C::SetDispBG(bool is_disp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SlotSelecterBack_C", "SetDispBG");

	Params::SlotSelecterBack_C_SetDispBG Parms{};

	Parms.is_disp = is_disp;

	UObject::ProcessEvent(Func, &Parms);
}

}

