#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundMode

#include "Basic.hpp"

#include "SoundMode_classes.hpp"
#include "SoundMode_parameters.hpp"


namespace SDK
{

// Function SoundMode.SoundMode_C.ExecuteUbergraph_SoundMode
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::ExecuteUbergraph_SoundMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "ExecuteUbergraph_SoundMode");

	Params::SoundMode_C_ExecuteUbergraph_SoundMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundMode.SoundMode_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// const class UWidgetAnimation*           Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "OnAnimationFinished");

	Params::SoundMode_C_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundMode.SoundMode_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "Tick");

	Params::SoundMode_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundMode.SoundMode_C.OnPressedButton
// (Event, Public, BlueprintEvent)

void USoundMode_C::OnPressedButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "OnPressedButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.Start
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>&OnStepChanged                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
// int32                                   ZOrder                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::Start(const TDelegate<void(const class FName& OldStep, const class FName& NewStep, bool NewStepIsEndStep)>& OnStepChanged, int32 ZOrder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "Start");

	Params::SoundMode_C_Start Parms{};

	Parms.OnStepChanged = OnStepChanged;
	Parms.ZOrder = ZOrder;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundMode.SoundMode_C.Initialize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USoundMode_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.OnSelectBGM
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::OnSelectBGM()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "OnSelectBGM");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.OnSelectSE
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::OnSelectSE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "OnSelectSE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.OnSelectVoice
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::OnSelectVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "OnSelectVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.OnSelectMsg
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::OnSelectMsg()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "OnSelectMsg");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.GetSelectTab
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundMenuSet_C**                 Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::GetSelectTab(class USoundMenuSet_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "GetSelectTab");

	Params::SoundMode_C_GetSelectTab Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function SoundMode.SoundMode_C.MoveTab
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Move                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::MoveTab(int32 Move)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "MoveTab");

	Params::SoundMode_C_MoveTab Parms{};

	Parms.Move = Move;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundMode.SoundMode_C.UpdateMenu
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::UpdateMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "UpdateMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.UpdateSoundTitle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundMenuSet_C*                  List                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundMode_C::UpdateSoundTitle(class USoundMenuSet_C* List)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "UpdateSoundTitle");

	Params::SoundMode_C_UpdateSoundTitle Parms{};

	Parms.List = List;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundMode.SoundMode_C.UpdateControllGuide
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::UpdateControllGuide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "UpdateControllGuide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundMode.SoundMode_C.GetPlayState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsPlay                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USoundMode_C::GetPlayState(bool* IsPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "GetPlayState");

	Params::SoundMode_C_GetPlayState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsPlay != nullptr)
		*IsPlay = Parms.IsPlay;
}


// Function SoundMode.SoundMode_C.CloseMenu
// (Public, BlueprintCallable, BlueprintEvent)

void USoundMode_C::CloseMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundMode_C", "CloseMenu");

	UObject::ProcessEvent(Func, nullptr);
}

}

