#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TitleMainMenu

#include "Basic.hpp"

#include "TitleMainMenu_classes.hpp"
#include "TitleMainMenu_parameters.hpp"


namespace SDK
{

// Function TitleMainMenu.TitleMainMenu_C.ExecuteUbergraph_TitleMainMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::ExecuteUbergraph_TitleMainMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "ExecuteUbergraph_TitleMainMenu");

	Params::TitleMainMenu_C_ExecuteUbergraph_TitleMainMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleMainMenu.TitleMainMenu_C.PlayOpen
// (BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::PlayOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "PlayOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.OnPressedButton
// (Event, Public, BlueprintEvent)

void UTitleMainMenu_C::OnPressedButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "OnPressedButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "Tick");

	Params::TitleMainMenu_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleMainMenu.TitleMainMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UTitleMainMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UTitleMainMenu_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "PreConstruct");

	Params::TitleMainMenu_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleMainMenu.TitleMainMenu_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.SetupMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::SetupMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "SetupMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.Clear
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.Refresh
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.AddMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UTitleMenuItem_C*&          add_menu                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::AddMenu(const class UTitleMenuItem_C*& add_menu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "AddMenu");

	Params::TitleMainMenu_C_AddMenu Parms{};

	Parms.add_menu = add_menu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleMainMenu.TitleMainMenu_C.GetMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTitleMenuItem_C**                Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::GetMenu(int32 Param_Index_0, class UTitleMenuItem_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "GetMenu");

	Params::TitleMainMenu_C_GetMenu Parms{};

	Parms.Param_Index_0 = Param_Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function TitleMainMenu.TitleMainMenu_C.GetSelectMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTitleMenuItem_C**                Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::GetSelectMenu(class UTitleMenuItem_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "GetSelectMenu");

	Params::TitleMainMenu_C_GetSelectMenu Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function TitleMainMenu.TitleMainMenu_C.MoveCursor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Move                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::MoveCursor(int32 Move)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "MoveCursor");

	Params::TitleMainMenu_C_MoveCursor Parms{};

	Parms.Move = Move;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleMainMenu.TitleMainMenu_C.ActivateMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTitleMenuItem_C*                 ターゲット                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::ActivateMenu(class UTitleMenuItem_C* ターゲット)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "ActivateMenu");

	Params::TitleMainMenu_C_ActivateMenu Parms{};

	Parms.ターゲット = ターゲット;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleMainMenu.TitleMainMenu_C.DecideMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::DecideMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "DecideMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleMainMenu.TitleMainMenu_C.GetSelectMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            Mode                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleMainMenu_C::GetSelectMode(class FName* Mode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "GetSelectMode");

	Params::TitleMainMenu_C_GetSelectMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Mode != nullptr)
		*Mode = Parms.Mode;
}


// Function TitleMainMenu.TitleMainMenu_C.InitializeCursorByLastGameMode
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleMainMenu_C::InitializeCursorByLastGameMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleMainMenu_C", "InitializeCursorByLastGameMode");

	UObject::ProcessEvent(Func, nullptr);
}

}

