#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TitleExtraMenu

#include "Basic.hpp"

#include "TitleExtraMenu_classes.hpp"
#include "TitleExtraMenu_parameters.hpp"


namespace SDK
{

// Function TitleExtraMenu.TitleExtraMenu_C.ExecuteUbergraph_TitleExtraMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::ExecuteUbergraph_TitleExtraMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "ExecuteUbergraph_TitleExtraMenu");

	Params::TitleExtraMenu_C_ExecuteUbergraph_TitleExtraMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleExtraMenu.TitleExtraMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UTitleExtraMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleExtraMenu_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleExtraMenu_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.SetupMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleExtraMenu_C::SetupMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "SetupMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.Clear
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleExtraMenu_C::Clear()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "Clear");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.Refresh
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleExtraMenu_C::Refresh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "Refresh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.AddMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTitleMenuItem_C*                 add_menu                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::AddMenu(class UTitleMenuItem_C* add_menu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "AddMenu");

	Params::TitleExtraMenu_C_AddMenu Parms{};

	Parms.add_menu = add_menu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleExtraMenu.TitleExtraMenu_C.GetMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Input                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTitleMenuItem_C**                Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::GetMenu(int32 Input, class UTitleMenuItem_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "GetMenu");

	Params::TitleExtraMenu_C_GetMenu Parms{};

	Parms.Input = Input;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function TitleExtraMenu.TitleExtraMenu_C.GetSelectMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTitleMenuItem_C**                Output                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::GetSelectMenu(class UTitleMenuItem_C** Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "GetSelectMenu");

	Params::TitleExtraMenu_C_GetSelectMenu Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function TitleExtraMenu.TitleExtraMenu_C.MoveCursor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Move                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::MoveCursor(int32 Move)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "MoveCursor");

	Params::TitleExtraMenu_C_MoveCursor Parms{};

	Parms.Move = Move;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleExtraMenu.TitleExtraMenu_C.ActivateMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTitleMenuItem_C*                 add_menu                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::ActivateMenu(class UTitleMenuItem_C* add_menu)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "ActivateMenu");

	Params::TitleExtraMenu_C_ActivateMenu Parms{};

	Parms.add_menu = add_menu;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TitleExtraMenu.TitleExtraMenu_C.GetSelectMode
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            Mode                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::GetSelectMode(class FName* Mode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "GetSelectMode");

	Params::TitleExtraMenu_C_GetSelectMode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Mode != nullptr)
		*Mode = Parms.Mode;
}


// Function TitleExtraMenu.TitleExtraMenu_C.InitializeCursorByLastGameMode
// (Public, BlueprintCallable, BlueprintEvent)

void UTitleExtraMenu_C::InitializeCursorByLastGameMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "InitializeCursorByLastGameMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TitleExtraMenu.TitleExtraMenu_C.GetIndexOfMenu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UTitleMenuItem_C*                 TitleMenuItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  menuIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTitleExtraMenu_C::GetIndexOfMenu(class UTitleMenuItem_C* TitleMenuItem, int32* menuIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TitleExtraMenu_C", "GetIndexOfMenu");

	Params::TitleExtraMenu_C_GetIndexOfMenu Parms{};

	Parms.TitleMenuItem = TitleMenuItem;

	UObject::ProcessEvent(Func, &Parms);

	if (menuIndex != nullptr)
		*menuIndex = Parms.menuIndex;
}

}

